---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/21 0021 19:01
---

--七伤拳
function OF()
    return GetUnitAbilityLevel(GetAttacker(), 1093678925) >= 1 and IsUnitEnemy(GetTriggerUnit(), GetOwningPlayer(GetAttacker()))
end
function PF()
    local id = GetHandleId(GetTriggeringTrigger())
    return IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(LoadUnitHandle(YDHT, id * LoadInteger(YDHT, id, -320330265), 1505665227))) and IsUnitAliveBJ(GetFilterUnit())
end
function QF()
    local u = GetAttacker()
    local uc = GetEnumUnit()
    local loc = GetUnitLoc(uc)
    local i = 1 + GetPlayerId(GetOwningPlayer(u))
    local shxishu = 1.0
    local shanghai = 0.0
    DestroyEffect(AddSpecialEffectLocBJ(loc, "war3mapImported\\PhoenixAttack.mdx"))
    if GetUnitAbilityLevel(u, 1093678928) ~= 0 and GetUnitAbilityLevel(u, 1093678919) ~= 0 and GetUnitAbilityLevel(u, 1093679156) ~= 0 and GetUnitAbilityLevel(u, 1093678936) ~= 0 and GetUnitAbilityLevel(u, 1093678933) ~= 0 and GetUnitAbilityLevel(u, 1395666994) ~= 0 and GetUnitAbilityLevel(u, 1093678672) ~= 0 then
        shxishu = shxishu * 7 * 2
    end
    shanghai = ShangHaiGongShi(u, uc, 12.0, 16.0, shxishu, 1093678925)
    WuGongShangHai(u, uc, shanghai)
    if GetUnitAbilityLevel(u, 1093678928) ~= 0 and GetRandomReal(0.0, 100.0) <= 5.0 and UnitHasBuffBJ(uc, 1110454322) == false then
        general_buff(u, uc, 1)
    end
    if GetUnitAbilityLevel(u, 1093678919) ~= 0 and GetRandomReal(0.0, 100.0) <= 10.0 and UnitHasBuffBJ(uc, 1111844210) == false then
        general_buff(u, uc, 8)
    end
    if GetUnitAbilityLevel(u, 1093679156) ~= 0 and GetRandomReal(0.0, 100.0) <= 10.0 and UnitHasBuffBJ(uc, 1111847784) == false then
        general_buff(u, uc, 13)
    end
    if GetUnitAbilityLevel(u, 1093678936) ~= 0 and GetRandomReal(0.0, 100.0) <= 10.0 and UnitHasBuffBJ(uc, 1110454323) == false then
        general_buff(u, uc, 3)
    end
    if GetUnitAbilityLevel(u, 1093678933) ~= 0 and GetRandomReal(0.0, 100.0) <= 10.0 and UnitHasBuffBJ(uc, 1113813609) == false then
        general_buff(u, uc, 4)
    end
    if GetUnitAbilityLevel(u, 1395666994) ~= 0 and GetRandomReal(0.0, 100.0) <= 10.0 and UnitHasBuffBJ(uc, 1110454326) == false then
        general_buff(u, uc, 6)
    end
    if GetUnitAbilityLevel(u, 1093678672) ~= 0 and GetRandomReal(0.0, 100.0) <= 10.0 and UnitHasBuffBJ(uc, 1110454328) == false then
        general_buff(u, uc, 11)
    end
    RemoveLocation(loc)
    u = nil
    uc = nil
    loc = nil
end
function RF()
    local id = GetHandleId(GetTriggeringTrigger())
    local cx = LoadInteger(YDHT, id, -807506826)
    cx = cx + 3
    SaveInteger(YDHT, id, -807506826, cx)
    SaveInteger(YDHT, id, -320330265, cx)
    YDWELocalVariableInitiliation()
    SaveUnitHandle(YDHT, id * cx, 1505665227, GetAttacker())
    SaveLocationHandle(YDHT, id * cx, -1925439584, GetUnitLoc(GetTriggerUnit()))
    SaveLocationHandle(YDHT, id * cx, -860413970, GetUnitLoc(GetAttacker()))
    SaveInteger(YDHT, id * cx, -708948899, 1093678925)
    SaveReal(YDHT, id * cx, 596788346, 25.0)
    SaveReal(YDHT, id * cx, 1097940387, 500.0)
    SaveReal(YDHT, id * cx, -753873030, 3.0 + I2R(GetUnitAbilityLevel(LoadUnitHandle(YDHT, id * cx, 1505665227), LoadInteger(YDHT, id * cx, -708948899))) / 2.0 + I2R(danpo[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))]) * 0.06)
    SaveReal(YDHT, id * cx, 426308609, 1.5 + udg_shanghaijiacheng[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))])
    SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * LoadReal(YDHT, id * cx, 426308609))
    if GetUnitAbilityLevel(LoadUnitHandle(YDHT, id * cx, 1505665227), LoadInteger(YDHT, id * cx, -708948899)) == 9 then
        SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * 10.0)
    end
    if GetRandomReal(0.0, 100.0) <= LoadReal(YDHT, id * cx, 596788346) then
        ForGroupBJ(YDWEGetUnitsInRangeOfLocMatchingNull(LoadReal(YDHT, id * cx, 1097940387), LoadLocationHandle(YDHT, id * cx, -1925439584), Condition(PF)), QF)
        WuGongShengChong(GetAttacker(), 1093678925, 2000.0)
    end
    RemoveLocation(LoadLocationHandle(YDHT, id * cx, -1925439584))
    RemoveLocation(LoadLocationHandle(YDHT, id * cx, -860413970))
    YDWELocalVariableEnd()
    FlushChildHashtable(YDHT, id * cx)
end

t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_ATTACKED)
TriggerAddCondition(t, Condition(OF))
TriggerAddAction(t, RF)