---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/21 0021 19:01
---

--- 七伤拳

--- @param source unit 攻击来源
--- @param target unit 被攻击的单位
et.game:event '单位-受攻击'(function(self, source, target)
    if source:has_ability(1093678925) and source:is_enemy(target) then
        if commonutil.random(0, 100) <= 25 then
            local group = et.selector():in_range(target:get_point(), 500):is_enemy(source):get()
            local coeff = 1
            if source:has_all_abilities(1093678928, 1093678919, 1093679156, 1093678936, 1093678933, 1395666994, 1093678672) then
                coeff = coeff * 14
            end
            for _, v in pairs(group) do
                local ability_damage, critical = damage_formula {
                    source = source,
                    target = v,
                    magic_coeff = 1.2,
                    physic_coeff = 1.6,
                    ability_coeff = 10 * coeff,
                    level = source:get_ability_level(1093678925)
                }
                et.effect.add_to_point("war3mapImported\\PhoenixAttack.mdx", v:get_point()):destroy()
                apply_damage(source, v, ability_damage, critical)
                if source:has_ability(1093678928) and commonutil.random(0, 100) <= 5 and not source:has_buff(1110454322) then
                    source:apply_buff(v, "内伤")
                end
                if source:has_ability(1093678919) and commonutil.random(0, 100) <= 10 and not source:has_buff(1111844210) then
                    source:apply_buff(v, "麻痹")
                end
                if source:has_ability(1093679156) and commonutil.random(0, 100) <= 10 and not source:has_buff(1111847784) then
                    source:apply_buff(v, "中毒")
                end
                if source:has_ability(1093678936) and commonutil.random(0, 100) <= 10 and not source:has_buff(1110454323) then
                    source:apply_buff(v, "流血")
                end
                if source:has_ability(1093678933) and commonutil.random(0, 100) <= 10 and not source:has_buff(1113813609) then
                    source:apply_buff(v, "混乱")
                end
                if source:has_ability(1395666994) and commonutil.random(0, 100) <= 10 and not source:has_buff(1110454326) then
                    source:apply_buff(v, "重伤")
                end
                if source:has_ability(1093678672) and commonutil.random(0, 100) <= 10 and not source:has_buff(1110454328) then
                    source:apply_buff(v, "封穴")
                end
            end
        end
    end
end)

