---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/21 0021 19:02
---

--九阴白骨爪
function TF()
    return GetEventDamage() == 0.35
end
function UF()
    local i = 1 + GetPlayerId(GetOwningPlayer(GetEventDamageSource()))
    local u = udg_hero[i]
    local uc = GetTriggerUnit()
    local shxishu = 1.0
    local shanghai = 0.0
    if GetUnitAbilityLevel(u, 1093678930) ~= 0 then
        shxishu = shxishu + 0.5
    end
    if GetUnitAbilityLevel(u, 1093678664) ~= 0 then
        shxishu = shxishu + 0.6
    end
    if GetUnitAbilityLevel(u, 1093679161) ~= 0 then
        shxishu = shxishu + 0.7
    end
    if GetUnitAbilityLevel(u, 1093678931) ~= 0 then
        shxishu = shxishu + 0.8
    end
    if GetUnitAbilityLevel(u, 1093679154) ~= 0 then
        shxishu = shxishu + 0.6
    end
    if udg_whichzhangmen[1 + GetPlayerId(GetOwningPlayer(u))] == 11 then
        shxishu = shxishu * 20
    end
    if GetUnitAbilityLevel(u, 1093678930) ~= 0 and GetUnitAbilityLevel(u, 1093678664) ~= 0 and GetUnitAbilityLevel(u, 1093679161) ~= 0 and GetUnitAbilityLevel(u, 1093678931) ~= 0 and GetUnitAbilityLevel(u, 1093679154) ~= 0 then
        shxishu = shxishu * 5 * 2
    end
    shanghai = ShangHaiGongShi(u, uc, 36, 36, shxishu, 1093678926)
    WuGongShangHai(u, uc, shanghai)
    WuGongShengChong(GetEventDamageSource(), 1093678926, 3000.0)
    u = nil
    uc = nil
end

t = CreateTrigger()
YDWESyStemAnyUnitDamagedRegistTrigger(t)
TriggerAddCondition(t, Condition(TF))
TriggerAddAction(t, UF)