---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/21 0021 18:10
---

--- 化骨绵掌
--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target unit|point|nil 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093678668 and u:is_hero() then
        if u:has_ability(1093678929) then
            local group = et.selector():in_range(target:get_point(), 1000):is_enemy(u):add_filter(function(ut)
                return not ut:has_buff(1114467444)
            end)
            local function shoot_one()
                dummy_issue_order {
                    target = group:random(),
                    player = u:get_owner(),
                    unit_id = 1697656880,
                    ability_id = 1093678668,
                    ability_level = u:get_ability_level(1093678668),
                    order_id = 852480,
                    lifetime = 10,
                }
            end
            for i = 1, 4 do
                shoot_one()
            end
        end
        if u:has_ability(1093678936) then
            u:add_ability(1093677139)
            --- FIXME 20秒后移除技能
            et.timer(500, 40, function(t)
                if not u:has_buff(1114467427) then
                    u:remove_ability(1093678936)
                    t:remove()
                end
            end)

        end
    end
end)

--- 化骨绵掌伤害
--- @param source unit 伤害来源
--- @param target unit 受伤害的单位
--- @param damage number 伤害的数值
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if damage ~= 0.26 then
        return
    end
    local p = source:get_owner()
    local h = p.hero
    local coeff = 1 + h['经脉'] // 20
    coeff = coeff + (source:has_ability(1093678928) and 0.7 or 0)
    coeff = coeff + (source:has_ability(1093678919) and 0.7 or 0)
    coeff = coeff + (source:has_ability(1093679156) and 0.8 or 0)
    coeff = coeff * (source:has_all_abilities(1093678928, 1093678919, 1093679156, 1093678929, 1093678930, 1093678936) and 12 or 1)
    local ability_damage, critical = damage_formula {
        source = source,
        target = target,
        magic_coeff = 1,
        physic_coeff = 1,
        ability_coeff = 80 * coeff,
        level = source:get_ability_level(1093678668)
    }
    apply_damage(source, target, ability_damage, critical)

end)

