---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/21 0021 18:37
---

--- 四门刀法
--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target unit|point|nil 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093678669 and u:is_hero() then
        local lifetime = u:has_ability(1505665227) and 20 or 10
        local max = u:has_all_abilities(1093679158, 1093678936) and 8 or 4
        for i = 1, max do
            dummy_issue_order {
                player = u:get_owner(),
                point = u:get_point() - { 360 / max * i, 300 },
                unit_id = 1697656883,
                order_id = 852128,
                lifetime = lifetime,
                shown = true
            }
            dummy_issue_order {
                player = u:get_owner(),
                point = u:get_point() - { 360 / max * i, 300 },
                unit_id = 1697656884,
                lifetime = lifetime,
                shown = true
            }
        end
        if u:has_ability(1093678935) then
            dummy_issue_order {
                player = u:get_owner(),
                point = u:get_point(),
                unit_id = 1697656880,
                ability_id = 1093678670,
                lifetime = lifetime,
            }
        end
    end
end)

--- 四门刀法伤害
--- @param source unit 伤害来源
--- @param target unit 受伤害的单位
--- @param damage number 伤害的数值
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if damage ~= 0.27 then
        return
    end
    local coeff = 1
    coeff = coeff + (source:has_ability(1093678928) and 0.6 or 0)
    coeff = coeff + (source:has_all_abilities(1093679158, 1093678936) and 1.5 or 0)
    coeff = coeff * (source:has_all_abilities(1093678928, 1093679158, 1093678936, 1093678935, 1093678920) and 10 or 1)
    local ability_damage, critical = damage_formula {
        source = source,
        target = target,
        magic_coeff = 1,
        physic_coeff = 1,
        ability_coeff = 7.2 * coeff,
        level = source:get_ability_level(1093678669)
    }
    apply_damage(source, target, ability_damage, critical)
end)

