---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/19 17:02
---

--- 弹指神通
--- @param u unit
--- @param id number
--- @param target unit|point|nil
et.game:event '单位-技能生效'(function(self, u, id, target)
    --- 弹指神通+双手互搏
    if id == 1093678664 and u:is_hero() and u:has_ability(1093678933) then
        local ur = et.selector():in_range(target:get_point(), 300):is_enemy(u):random()
        dummy_issue_order {
            target = ur,
            player = u:get_owner(),
            ability_id = 1093678664,
            ability_level = u:get_ability_level(1093678664),
            order_id = 852119,
            lifetime = 2
        }
    end
end)

--- 九阴真经·内功 + 弹指 = 被动
--- @param source unit 攻击来源
--- @param target unit 被攻击的单位
et.game:event '单位-受攻击'(function(self, source, target)
    if source:has_all_abilities(1093678664, 1093678931) and commonutil.random(0, 100) <= 8 then
        dummy_issue_order {
            target = target,
            player = source:get_owner(),
            ability_id = 1093678664,
            ability_level = source:get_ability_level(1093678664),
            order_id = 852119,
            lifetime = 2,
        }
    end
end)

--- 弹指神通技能伤害
--- @param source unit 伤害来源
--- @param target unit 受伤害的单位
--- @param damage number 伤害的数值
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if damage ~= 0.21 then
        return
    end
    local coeff = 1
    coeff = coeff + source:has_ability(1093678672) and 0.6 or 0
    coeff = coeff + source:has_ability(1093679157) and 0.7 or 0
    coeff = coeff * (source:has_all_abilities(1093678672, 1093679157, 1093679152, 1395666994, 1093678933, 1093678931) and 12 or 1)
    local ability_damage, critical = damage_formula {
        source = source,
        target = target,
        magic_coeff = 1,
        physic_coeff = 1,
        ability_coeff = 30.8 * coeff,
        level = source:get_ability_level(1093678664)
    }
    apply_damage(source, target, ability_damage, critical)
    local p = source:get_owner()
    local h = p.hero
    if h['胆魄'] >= 23 and commonutil.random(0, 100) <= 30 and not target:has_buff(1110454328) then
        source:apply_buff(target, "封穴")
    end
    if source:has_ability(1093679152) and not target:has_buff(1113813609) then
        source:apply_buff(target, "混乱")
    end
    if source:has_ability(1395666994) then
        et.effect.add_to_point("war3mapImported\\PsiWave.mdx", target:get_point()):destroy()
        local group = et.selector():in_range(target:get_point(), 100):is_enemy(source):get()
        for _, v in pairs(group) do
            apply_damage(source, target, ability_damage, critical)
        end
    end
end)
