---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/19 17:02
---

--弹指神通
function IsTanZhi()
    return GetSpellAbilityId() == 1093678664 and IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) ~= nil -- INLINED!!
end
function TanZhi_Condition()
    return IsUnitAliveBJ(GetFilterUnit()) and IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(GetTriggerUnit()))
end
function TanZhiShenTong()
    local u = GetTriggerUnit()
    local p = GetOwningPlayer(u)
    local loc = GetUnitLoc(u)
    local loc2 = GetUnitLoc(GetSpellTargetUnit())
    local i = 1 + GetPlayerId(p)
    if GetUnitAbilityLevel(u, 1093678933) >= 1 then
        CreateNUnitsAtLoc(1, 1697656880, p, loc, bj_UNIT_FACING)
        UnitAddAbility(bj_lastCreatedUnit, 1093678664)
        SetUnitAbilityLevel(bj_lastCreatedUnit, 1093678664, GetUnitAbilityLevel(u, 1093678664))
        IssueTargetOrderById(bj_lastCreatedUnit, 852119, GroupPickRandomUnit(YDWEGetUnitsInRangeOfLocMatchingNull(300, loc2, Condition(TanZhi_Condition))))
        UnitApplyTimedLife(bj_lastCreatedUnit, 1112045413, 2.0)
        ShowUnitHide(bj_lastCreatedUnit)
    end
    WuGongShengChong(GetTriggerUnit(), 1093678664, 350.0)
    RemoveLocation(loc)
    RemoveLocation(loc2)
    u = nil
    p = nil
    loc = nil
    loc2 = nil
end
function IsTanZhiBeiDong()
    return GetUnitAbilityLevel(GetAttacker(), 1093678664) >= 1 and GetUnitAbilityLevel(GetAttacker(), 1093678931) >= 1
end
function TanZhiBeiDong()
    local u = GetAttacker()
    local l__ut = GetTriggerUnit()
    local loc = GetUnitLoc(u)
    local p = GetOwningPlayer(u)
    if GetRandomReal(0, 100) <= 8 then
        CreateNUnitsAtLoc(1, 1697656880, p, loc, bj_UNIT_FACING)
        UnitAddAbility(bj_lastCreatedUnit, 1093678664)
        SetUnitAbilityLevel(bj_lastCreatedUnit, 1093678664, GetUnitAbilityLevel(u, 1093678664))
        IssueTargetOrderById(bj_lastCreatedUnit, 852119, l__ut)
        UnitApplyTimedLife(bj_lastCreatedUnit, 1112045413, 2.0)
        ShowUnitHide(bj_lastCreatedUnit)
    end
    RemoveLocation(loc)
    u = nil
    l__ut = nil
    p = nil
end
function IsTanZhiShangHai()
    return GetEventDamage() == 0.21
end
function TanZhiShangHai_Conditiom()
    return IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(GetEventDamageSource())) and IsUnitAliveBJ(GetFilterUnit())
end
function TanZhiShangHai_Action()
    local i = 1 + GetPlayerId(GetOwningPlayer(GetEventDamageSource()))
    local u = udg_hero[i]
    local uc = GetEnumUnit()
    local shxishu = 1.0
    local shanghai = 0.0
    shanghai = ShangHaiGongShi(u, uc, 30.8, 30.8, shxishu, 1093678664)
    WuGongShangHai(u, uc, shanghai)
    u = nil
    uc = nil
end
function TanZhiShangHai()
    local i = 1 + GetPlayerId(GetOwningPlayer(GetEventDamageSource()))
    local u = udg_hero[i]
    local uc = GetTriggerUnit()
    local shxishu = 1.0
    local shanghai = 0.0
    local loc = GetUnitLoc(u)
    local loc2 = GetUnitLoc(uc)
    if GetUnitAbilityLevel(u, 1093678672) ~= 0 then
        shxishu = shxishu + 0.6
    end
    if GetUnitAbilityLevel(u, 1093679157) ~= 0 then
        shxishu = shxishu + 0.7
    end
    if GetUnitAbilityLevel(u, 1093679157) ~= 0 and GetUnitAbilityLevel(u, 1093678672) ~= 0 and GetUnitAbilityLevel(u, 1093679152) ~= 0 and GetUnitAbilityLevel(u, 1093679152) ~= 0 and GetUnitAbilityLevel(u, 1395666994) ~= 0 and GetUnitAbilityLevel(u, 1093678933) ~= 0 then
        shxishu = shxishu * 6 * 2
    end
    shanghai = ShangHaiGongShi(u, uc, 30.8, 30.8, shxishu, 1093678664)
    WuGongShangHai(u, uc, shanghai)
    if danpo[i] >= 23 and GetRandomReal(0.0, 100.0) <= 30.0 and UnitHasBuffBJ(uc, 1110454328) == false then
        general_buff(u, uc, 11)
    end
    if GetUnitAbilityLevel(u, 1093679152) ~= 0 and UnitHasBuffBJ(uc, 1113813609) == false then
        general_buff(u, uc, 4)
    end
    if GetUnitAbilityLevel(u, 1395666994) ~= 0 then
        DestroyEffect(AddSpecialEffectLocBJ(loc2, "war3mapImported\\PsiWave.mdx"))
        ForGroupBJ(YDWEGetUnitsInRangeOfLocMatchingNull(100.0, loc2, Condition(TanZhiShangHai_Conditiom)), TanZhiShangHai_Action)
    end
    RemoveLocation(loc)
    RemoveLocation(loc2)
    u = nil
    uc = nil
    loc = nil
    loc2 = nil
end

local t = CreateTrigger()
t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_SPELL_EFFECT)
TriggerAddCondition(t, Condition(IsTanZhi))
TriggerAddAction(t, TanZhiShenTong)
t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_ATTACKED)
TriggerAddCondition(t, Condition(IsTanZhiBeiDong))
TriggerAddAction(t, TanZhiBeiDong)
t = CreateTrigger()
YDWESyStemAnyUnitDamagedRegistTrigger(t)
TriggerAddCondition(t, Condition(IsTanZhiShangHai))
TriggerAddAction(t, TanZhiShangHai)