---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/21 0021 19:03
---

--- 空明拳
--- @param source unit 攻击来源
--- @param target unit 被攻击的单位
et.game:event '单位-受攻击'(function(self, source, target)
    if source:has_ability(1093677367) and commonutil.random(0, 100) <= 18 then
        local group = {}
        if source:has_ability(1093678933) then
            group = et.selector():in_range(target:get_point(), 400):is_enemy(source):get()
        else
            table.insert(group, target)
        end
        local coeff = 1
        coeff = coeff + (source:has_ability(1093678931) and 0.6 or 0)
        coeff = coeff + (source:has_ability(1093682225) and 0.8 or 0)
        coeff = coeff * (source:has_all_abilities(1093678931, 1093682225, 1093678672, 1093678933, 1093677368) and 10 or 1)
        for _, v in pairs(group) do
            local ability_damage, critical = damage_formula {
                source = source,
                target = v,
                magic_coeff = 1,
                physic_coeff = 0.8,
                ability_coeff = 10 * coeff,
                level = source:get_ability_level(1093677367)
            }
            apply_damage(source, v, ability_damage, critical)
            et.effect.add_to_unit("Units\\NightElf\\Wisp\\WispExplode.mdl", v, "overhead")
            if source:has_ability(1093678672) and commonutil.random(0, 100) <= 50 and not v:has_buff(1113813609) then
                source:apply_buff(v, "混乱")
            end
        end
    end
    --- 空明拳挨打
    if target:has_all_abilities(1093677367, 1093677368) and target:is_hero() then
        local h = target:get_owner().hero
        if h.kong_ming_value and h.kong_ming_value >= 100 then
            h.kong_ming_value = 0
            target:add_item(1920168051)
        else
            h.kong_ming_value = h.kong_ming_value or 0 + 1
        end
    end
end)