---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/20 9:52
---

--- 连城剑法
--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target point 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    local angle = u:get_point() / target
    local pt1 = u:get_point() - { angle + 120, 200 } - { angle, 150 }
    local pt2 = u:get_point() - { angle + 240, 200 } - { angle, 150 }
    if id == 1093678666 and u:is_hero() then
        local function shoot_one(pt)
            dummy_issue_order {
                target = pt,
                player = u:get_owner(),
                unit_id = 1697656880,
                ability_id = 1093678666,
                ability_level = u:get_ability_level(1093678666),
                order_id = 852218,
                lifetime = 2 }
        end
        shoot_one(pt1)
        shoot_one(pt2)
        if u:has_all_abilities(1093678932, 1093678918) then
            local pt3 = u:get_point() - { angle + 120, 550 } - { angle, 150 }
            local pt4 = u:get_point() - { angle + 240, 550 } - { angle, 150 }
            local pt5 = u:get_point() - { angle + 120, 400 } - { angle, 150 }
            local pt6 = u:get_point() - { angle + 240, 400 } - { angle, 150 }
            shoot_one(pt3)
            shoot_one(pt4)
            shoot_one(pt5)
            shoot_one(pt6)
        elseif u:has_any_ability(1093678932, 1093678918) then
            local pt5 = u:get_point() - { angle + 120, 400 } - { angle, 150 }
            local pt6 = u:get_point() - { angle + 240, 400 } - { angle, 150 }
            shoot_one(pt5)
            shoot_one(pt6)
        end
    end
end)

--- @param source unit 伤害来源
--- @param target unit 受伤害单位
--- @param damage number 伤害数值
et.game:event '单位-受到伤害' (function(self, source, target, damage)
    if damage ~= 0.23 then
        return
    end
    local coeff = 1
    coeff = coeff + (source:has_ability(1093678922) and 0.7 or 0)
    coeff = coeff + (source:has_ability(1093678936) and 0.8 or 0)
    coeff = coeff * (source:has_all_abilities(1093678922,1093678936,1093678932, 1093678918) and 8 or 1)
    local ability_damage, critical = damage_formula {
        source = source,
        target = target,
        magic_coeff = 1,
        physic_coeff = 1,
        ability_coeff = 53 * coeff,
        level = source:get_ability_level(1093678666)
    }
    apply_damage(source, target, ability_damage, critical)
end)

