---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/5 10:16
---

local log = require('jass.log')

function test_log_debug()
    log.debug('debug')
end

function test_log_info()
    log.info('info')
end

function test_log_warn()
    log.warn('warn')
end

function test_log_error()
    log.error('error')
end

local function main()
    test_log_debug()
    test_log_info()
    test_log_warn()
    test_log_error()
end

main()