---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/1 13:38
---

local jass = require 'jass.common'

local function test_CreateUnit()
    u = jass.CreateUnit({type = 'player'}, 12345, 100, 100, 270)
    print(u)
end

local function test_CreateUnitByName()
    u, error = pcall(jass.CreateUnitByName, {}, '12345', 100, 100, 270)
    print(u, error)
end

local function test_CreateUnitAtLoc()
    u = jass.CreateUnitAtLoc({type = 'player'}, 12345, {type='location', x=150, y=150}, 270)
    print(u)
end

local function main()
    test_CreateUnit()
    test_CreateUnitByName()
    test_CreateUnitAtLoc()
end

main()