---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/1 11:46
---

local common = require 'jass.util.common_util'

local function test_generate_handle_id()
    print(common.generate_handle_id())
    print(common.generate_handle_id())
    print(common.generate_handle_id())
    print(common.generate_handle_id())
end

local function main()
    test_generate_handle_id()
end
main()