---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/26 9:00
---

--- @class bag
local bag = {}

function bag:new()
    local b = {}
    setmetatable(b, self)
    self.__index = self
    return b
end

function bag:insert(element)
    self[element] = (self[element] or 0) + 1
end

function bag:remove(element)
    local count = self[element]
    self[element] = (count and count > 1) and count - 1 or nil
end

return bag