---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/30 14:33
---

---@class stack
local stack = {}

function stack:new()
    local s = setmetatable({}, self)
    self.__index = self
    return s
end

--- @param element any
function stack:push(element)
    self[#self + 1] = element
end

--- @return any
function stack:pop()
    return table.remove(self)
end

--- @return any
function stack:peek()
    return self[#self]
end


return stack