---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/16 12:51
---

--BOSS AI放技能
function IsUnitBoss()
    return GetUnitPointValue(GetTriggerUnit()) == 101
end
function BossFangJiNeng()
    local u = GetTriggerUnit()
    local uc = GetEventDamageSource()
    local x = GetUnitX(uc)
    local y = GetUnitY(uc)
    if GetRandomInt(1, 100) < 50 then
        if GetUnitTypeId(GetTriggerUnit()) == u7[1] then
            IssuePointOrderById(u, 852600, x, y)
        elseif GetUnitTypeId(GetTriggerUnit()) == u7[2] then
            if GetRandomInt(1, 3) == 1 then
                IssueTargetOrderById(u, 852600, uc)
            elseif GetRandomInt(1, 2) == 1 then
                IssueImmediateOrderById(u, 852177)
            else
                IssueImmediateOrderById(u, 852178)
            end
        elseif GetUnitTypeId(GetTriggerUnit()) == u7[3] then
            IssuePointOrderById(u, 852600, x, y)
        elseif GetUnitTypeId(GetTriggerUnit()) == u7[4] then
            IssuePointOrderById(u, 852600, x, y)
        elseif GetUnitTypeId(GetTriggerUnit()) == u7[5] then
            IssueTargetOrder(u, "chemicalrage", u)
        elseif GetUnitTypeId(GetTriggerUnit()) == u7[6] then
            IssueTargetOrder(u, "devour", u)
        end
    end
    u = nil
    uc = nil
end

local function init()
    Bk = CreateTrigger()
    YDWESyStemAnyUnitDamagedRegistTrigger(Bk)
    TriggerAddCondition(Bk, Condition(IsUnitBoss))
    TriggerAddAction(Bk, BossFangJiNeng)
end
init()