local function init()

    require 'map.rules.BOSS技能'
    require 'map.rules.传送'
    require 'map.rules.伤害公式'
    require 'map.rules.伤害测试'
    require 'map.rules.partner_system'
    require 'map.rules.刷进攻怪'
    require 'map.rules.剑意'
    require 'map.rules.加入副职'
    require 'map.rules.古董系统'
    require 'map.rules.吃经验符'
    require 'map.rules.各类回复'
    require 'map.rules.合成物品'
    require 'map.rules.基地保护'
    require 'map.rules.学习武功'
    require 'map.rules.宠物技能'
    require 'map.rules.抽血术'
    require 'map.rules.攻破城门'
    require 'map.rules.整理物品'
    require 'map.rules.新手礼包'
    require 'map.rules.杀怪'
    require 'map.rules.查看属性'
    require 'map.rules.武功升重'
    require 'map.rules.武功效果'
    require 'map.rules.武学精要'
    require 'map.rules.游戏胜负'
    require 'map.rules.激活残章'
    require 'map.rules.特效'
    require 'map.rules.特殊事件'
    require 'map.rules.生成F9'
    require 'map.rules.离开游戏'
    require 'map.rules.积分商店'
    require 'map.rules.系统窗口'
    require 'map.rules.练功房'
    require 'map.rules.结拜'
    require 'map.rules.英雄升级'
    require 'map.rules.英雄死活'
    require 'map.rules.试玩模式'
    require 'map.rules.购买等级'
    require 'map.rules.轻功系统'
    require 'map.rules.选择模式'
    require 'map.rules.选择英雄'
    require 'map.rules.选择门派'
    require 'map.rules.选择难度'
    require 'map.rules.遗忘武功'
    require 'map.rules.野怪复活'
    require 'map.rules.预约名门'
    require 'map.rules.魔教救人'
end

init()



