---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/30 16:10
---

-- 历练远程传送
local teleport = {}
-- 终南山
teleport[1227896148] = {
    name = '终南山',
    level = 10,
    reputation = 500,
    rect = Te,
}
--少林寺后山
teleport[1227896149] = {
    name = '少林寺后山',
    level = 25,
    reputation = 1500,
    rect = ag,
}
--塞外
teleport[1227896150] = {
    name = '塞外',
    level = 40,
    reputation = 2500,
    rect = Bg,
}
--光明顶
teleport[1227896151] = {
    name = '光明顶',
    level = 55,
    reputation = 4000,
    rect = Lg,
}
--少林寺后山
teleport[1227896152] = {
    name = '少林寺后山',
    level = 70,
    reputation = 6000,
    rect = Rg,
}
--边疆
teleport[1227896385] = {
    name = '边疆',
    level = 100,
    reputation = 9000,
    rect = Zg,
}

-- 驿站
local post = {}
post[1227899472] = {
    name = '牛妖幻境',
    point = et.point(3763, -9091),
}
post[1227899473] = {
    name = '初入江湖',
    point = et.point(1446, -2317),
}
post[1227899474] = {
    name = '少林寺外',
    point = et.point(1863, 0),
}
post[1227899475] = {
    name = '光明顶下',
    point = et.point(-1476, 8139),
}
post[1227899476] = {
    name = '江南水乡',
    point = et.point(-2400, -3900),
}
post[1227899477] = {
    name = '全真三子',
    point = et.point(-4400, -2950),
}
post[1227899478] = {
    name = '雁门关内',
    point = et.point(-5960, -160),
}
post[1227899479] = {
    name = '大辽国',
    point = et.point(-13000, -15500),
}
post[1227899480] = {
    name = '聚贤庄',
    point = et.point(-9000, -14000),
}

local function init()
    et.game:event '单位-捡起物品' (function(self, u, item)
        local p = u:get_owner()
        local h = p.hero
        local te = teleport[jass.GetItemTypeId(item)]
        if u:is_hero() and p:is_player() and te then
            print(u:get_level())
            if u:get_level() < te.level then
                p:send_message("|cFFFF0000等级不足"..te.level.."级无法传送")
            else
                if h.reputation < te.reputation then
                    p:send_message("|cFFFF0000江湖声望不足"..te.reputation.."无法传送")
                else
                    local pos = et.get_rect_center(te.rect)
                    u:set_point(pos)
                    p:set_camera(pos)
                    p:send_message("|cff66ff33进入"..te.name)
                end
            end
        end
        local po = post[jass.GetItemTypeId(item)]
        if u:is_hero() and p:is_player() and po then
            u:set_point(po.point)
            p:send_message("|CFF00ff33传送至"..po.name)
        end
    end)
end
init()