---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/10/29 0029 20:07
---

--伤害测试桩
--[===[
（1）单位购买物品‘伤害测试’时，伤害测试单位由玩家6的单位（友方）变为玩家7的单位（敌方），并将正在测试的开关置为true
（2）测试持续10秒钟，期间伤害计入总伤害
（3）10秒后，测试结束，不再计算伤害，伤害测试单位的控制权回归玩家6（友方），同时向所有人展示测试总伤害
]===]

local function init()
    local test_creep = gg_unit_N00I_0116
    local test_damage = 0
    local is_testing = false
    -- 伤害测试
    et.game:event '单位-捡起物品'(function(self, u, item)
        if item:get_id() == 1227899447 then
            is_testing = true
            test_damage = 0
            force.send_message(test_creep:get_name())
            test_creep:set_owner(et.player(7))
            et.wait(10 * 1000, function()
                is_testing = false
                test_creep:set_owner(et.player(6))
                force.send_message("|cff00ff00测试总伤害为" .. test_damage)
            end)
        end
    end)
    test_creep:event '单位-受到伤害'(function(self, source, target, damage)
        if is_testing then
            test_damage = test_damage + damage
            log.debug('当前测试总伤害为：', test_damage)
        end
    end)
end

init()