---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/15 20:08
---

--古董价格
function s5()
    gudong[1] = 1227896115
    nd[1] = 500
    od[1] = 6000
    gudong[2] = 1227896116
    nd[2] = 500
    od[2] = 6000
    gudong[3] = 1227896117
    nd[3] = 500
    od[3] = 6000
    gudong[4] = 1227896118
    nd[4] = 1000
    od[4] = 20000
    gudong[5] = 1227896119
    nd[5] = 1000
    od[5] = 20000
    gudong[6] = 1227896120
    nd[6] = 1000
    od[6] = 20000
    gudong[7] = 1227896121
    nd[7] = 7000
    od[7] = 50000
    gudong[8] = 1227896129
    nd[8] = 7000
    od[8] = 50000
    gudong[9] = 1227896130
    nd[9] = 7000
    od[9] = 50000
    gudong[10] = 1227896131
    nd[10] = 20000
    od[10] = 100000
end
--古董价格变动
function u5()
    DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|cfffff000古董商人收购价格发生变动了~")
    pd[1] = GetRandomInt(nd[1], od[1])
    pd[2] = GetRandomInt(nd[2], od[2])
    pd[3] = GetRandomInt(nd[3], od[3])
    pd[4] = GetRandomInt(nd[4], od[4])
    pd[5] = GetRandomInt(nd[5], od[5])
    pd[6] = GetRandomInt(nd[6], od[6])
    pd[7] = GetRandomInt(nd[7], od[7])
    pd[8] = GetRandomInt(nd[8], od[8])
    pd[9] = GetRandomInt(nd[9], od[9])
    pd[10] = GetRandomInt(nd[10], od[10])
end
--查询古董价格
function w5()
    return GetItemTypeId(GetManipulatedItem()) == 1227896112
end
function x5()
    local u = GetTriggerUnit()
    local p = GetOwningPlayer(u)
    local i = 1
    i = 1
    for _ in _loop_() do
        if i > 10 then break end
        createitemloc(gudong[i], v7[9])
        if UnitHaveItem(u, gudong[i]) then
            DisplayTimedTextToPlayer(p, 0, 0, 30, "|cff00ff00" .. (GetItemName(bj_lastCreatedItem) or "") .. "：" .. (I2S(pd[i]) or "") .. " ( " .. (I2S(nd[i]) or "") .. " ， " .. (I2S(od[i]) or "") .. " )")
        else
            DisplayTimedTextToPlayer(p, 0, 0, 30, (GetItemName(bj_lastCreatedItem) or "") .. "：" .. (I2S(pd[i]) or "") .. " ( " .. (I2S(nd[i]) or "") .. " ， " .. (I2S(od[i]) or "") .. " )")
        end
        RemoveItem(bj_lastCreatedItem)
        i = i + 1
    end
    u = nil
    p = nil
end
--卖古董
function z5()
    return GetItemTypeId(GetManipulatedItem()) == 1227896113
end
function A5()
    local u = GetTriggerUnit()
    local p = GetOwningPlayer(u)
    local i = 1
    for _ in _loop_() do
        if i > 10 then break end
        if GetItemTypeId(UnitItemInSlotBJ(u, 1)) == gudong[i] then
            if Ce[1 + GetPlayerId(p)] ~= 4 then
                DisplayTimedTextToPlayer(p, 0, 0, 30, "|CFF00FF00卖出" .. (GetItemName(UnitItemInSlotBJ(u, 1)) or "") .. "，获得金钱+" .. (I2S(pd[i]) or ""))
                AdjustPlayerStateBJ(pd[i], p, PLAYER_STATE_RESOURCE_GOLD)
            else
                DisplayTimedTextToPlayer(p, 0, 0, 30, "|CFF00FF00你是鉴定师，以最高价格卖出" .. (GetItemName(UnitItemInSlotBJ(u, 1)) or "") .. "，获得金钱+" .. (I2S(od[i]) or ""))
                AdjustPlayerStateBJ(od[i], p, PLAYER_STATE_RESOURCE_GOLD)
            end
            RemoveItem(UnitItemInSlotBJ(u, 1))
        end
        i = i + 1
    end
    u = nil
    p = nil
end
function B5()
    return GetItemTypeId(GetManipulatedItem()) == 1227896114
end
function b5()
    local u = GetTriggerUnit()
    local p = GetOwningPlayer(u)
    local i = 1
    local j = 1
    j = 1
    for _ in _loop_() do
        if j > 6 then break end
        i = 1
        for _ in _loop_() do
            if i > 10 then break end
            if GetItemTypeId(UnitItemInSlotBJ(u, j)) == gudong[i] then
                if Ce[1 + GetPlayerId(p)] ~= 4 then
                    DisplayTimedTextToPlayer(p, 0, 0, 30, "|CFF00FF00卖出" .. (GetItemName(UnitItemInSlotBJ(u, j)) or "") .. "，获得金钱+" .. (I2S(pd[i]) or ""))
                    AdjustPlayerStateBJ(pd[i], GetOwningPlayer(GetTriggerUnit()), PLAYER_STATE_RESOURCE_GOLD)
                else
                    DisplayTimedTextToPlayer(p, 0, 0, 30, "|CFF00FF00你是鉴定师，以最高价格卖出" .. (GetItemName(UnitItemInSlotBJ(u, j)) or "") .. "，获得金钱+" .. (I2S(od[i]) or ""))
                    AdjustPlayerStateBJ(od[i], GetOwningPlayer(GetTriggerUnit()), PLAYER_STATE_RESOURCE_GOLD)
                end
                RemoveItem(UnitItemInSlotBJ(u, j))
            end
            i = i + 1
        end
        j = j + 1
    end
    u = nil
    p = nil
end
--收集古董
function CollectGuDong_Conditions()
    return GetItemTypeId(GetManipulatedItem()) == 1227897139 or GetItemTypeId(GetManipulatedItem()) == 1227897140 or GetItemTypeId(GetManipulatedItem()) == 1227897141 or GetItemTypeId(GetManipulatedItem()) == 1227897142
end
function CollectGuDong_Actions()
    local u = GetTriggerUnit()
    local p = GetOwningPlayer(u)
    local i = 1 + GetPlayerId(p)
    if GetItemTypeId(GetManipulatedItem()) == 1227897139 then
        if Ce[i] == 4 then
            if udg_gudongD == 0 then
                DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00我自幼喜欢收集古董，如果你能收集一套D等级古董，我将送你一本秘籍")
                udg_gudongD = 1
            else
                if UnitHaveItem(u, 1227896115) and UnitHaveItem(u, 1227896116) and UnitHaveItem(u, 1227896117) then
                    RemoveItem(FetchUnitItem(u, 1227896115))
                    RemoveItem(FetchUnitItem(u, 1227896116))
                    RemoveItem(FetchUnitItem(u, 1227896117))
                    DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00谢谢你的古董，这本江湖秘籍送给你了")
                    unitadditembyidswapped(udg_jianghu[GetRandomInt(1, 18)], u)
                    udg_jdds[i] = udg_jdds[i] + 2
                    if udg_jdds[i] <= 10 and udg_jddsbool[i] == false and Ce[i] == 4 then
                        DisplayTextToPlayer(p, 0, 0, "|CFF66FF00您的鉴定师已经得了" .. (I2S(udg_jdds[i]) or "") .. "分，得到10分可获得鉴定大师哦")
                    end
                    --if Ce[1+GetPlayerId(p)]==4 then
                    -- call unitadditembyidswapped(udg_jianghu[GetRandomInt(1,18)],u)
                    -- call DisplayTimedTextToPlayer(p,0,0,15,"|CFF00FF00谢谢你教我鉴定古董，再送你一本江湖秘籍吧")
                    --endif
                    udg_gudongD = 0
                else
                    DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00你还没有收集齐一套D古董哦")
                end
            end
        else
            DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00非鉴定师不能接此任务")
        end
    elseif GetItemTypeId(GetManipulatedItem()) == 1227897140 then
        if Ce[i] == 4 then
            if udg_gudongC == 0 then
                DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00我自幼喜欢收集古董，如果你能收集一套C等级古董，我将送你一本秘籍")
                udg_gudongC = 1
            else
                if UnitHaveItem(u, 1227896118) and UnitHaveItem(u, 1227896119) and UnitHaveItem(u, 1227896120) then
                    RemoveItem(FetchUnitItem(u, 1227896118))
                    RemoveItem(FetchUnitItem(u, 1227896119))
                    RemoveItem(FetchUnitItem(u, 1227896120))
                    DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00谢谢你的古董，这本绝学秘籍送给你了")
                    unitadditembyidswapped(udg_juexue[GetRandomInt(1, 10)], u)
                    udg_jdds[i] = udg_jdds[i] + 4
                    if udg_jdds[i] <= 10 and udg_jddsbool[i] == false and Ce[i] == 4 then
                        DisplayTextToPlayer(p, 0, 0, "|CFF66FF00您的鉴定师已经得了" .. (I2S(udg_jdds[i]) or "") .. "分，得到10分可获得鉴定大师哦")
                    end
                    --   if Ce[1+GetPlayerId(p)]==4 then
                    -- call unitadditembyidswapped(udg_juexue[GetRandomInt(1,10)],u)
                    -- call DisplayTimedTextToPlayer(p,0,0,15,"|CFF00FF00谢谢你教我鉴定古董，再送你一本绝学秘籍吧")
                    --endif
                    udg_gudongC = 0
                else
                    DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00你还没有收集齐一套C古董哦")
                end
            end
        else
            DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00非鉴定师不能接此任务")
        end
    elseif GetItemTypeId(GetManipulatedItem()) == 1227897141 then
        if Ce[i] == 4 then
            if udg_gudongB == 0 then
                DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00我自幼喜欢收集古董，如果你能收集一套B等级古董，我将送你一本秘籍")
                udg_gudongB = 1
            else
                if UnitHaveItem(u, 1227896121) and UnitHaveItem(u, 1227896129) and UnitHaveItem(u, 1227896130) then
                    RemoveItem(FetchUnitItem(u, 1227896121))
                    RemoveItem(FetchUnitItem(u, 1227896129))
                    RemoveItem(FetchUnitItem(u, 1227896130))
                    DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00谢谢你的古董，这本绝内秘籍送给你了")
                    unitadditembyidswapped(udg_juenei[GetRandomInt(1, 8)], u)
                    udg_jdds[i] = udg_jdds[i] + 6
                    if udg_jdds[i] <= 10 and udg_jddsbool[i] == false and Ce[i] == 4 then
                        DisplayTextToPlayer(p, 0, 0, "|CFF66FF00您的鉴定师已经得了" .. (I2S(udg_jdds[i]) or "") .. "分，得到10分可获得鉴定大师哦")
                    end
                    --   if Ce[1+GetPlayerId(p)]==4 then
                    -- call unitadditembyidswapped(udg_juenei[GetRandomInt(1,8)],u)
                    -- call DisplayTimedTextToPlayer(p,0,0,15,"|CFF00FF00谢谢你教我鉴定古董，再送你一本绝内秘籍吧")
                    --endif
                    udg_gudongB = 0
                else
                    DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00你还没有收集齐一套B古董哦")
                end
            end
        else
            DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00非鉴定师不能接此任务")
        end
    elseif GetItemTypeId(GetManipulatedItem()) == 1227897142 then
        if Ce[i] == 4 then
            if udg_gudongA == 0 then
                DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00我自幼喜欢收集古董，如果你能收集两个A等级古董，我将送你一本秘籍")
                udg_gudongA = 1
            else
                if UnitHaveItem(u, 1227896131) then
                    RemoveItem(FetchUnitItem(u, 1227896131))
                    if UnitHaveItem(u, 1227896131) then
                        RemoveItem(FetchUnitItem(u, 1227896131))
                        DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00谢谢你的古董，这本残章送给你了")
                        unitadditembyidswapped(udg_canzhang[GetRandomInt(1, 10)], u)
                        udg_jdds[i] = udg_jdds[i] + 10
                        if udg_jdds[i] <= 10 and udg_jddsbool[i] == false and Ce[i] == 4 then
                            DisplayTextToPlayer(p, 0, 0, "|CFF66FF00您的鉴定师已经得了" .. (I2S(udg_jdds[i]) or "") .. "分，得到10分可获得鉴定大师哦")
                        end
                        --   if Ce[1+GetPlayerId(p)]==4 then
                        -- call unitadditembyidswapped(udg_canzhang[GetRandomInt(1,10)],u)
                        -- call DisplayTimedTextToPlayer(p,0,0,15,"|CFF00FF00谢谢你教我鉴定古董，再送你一本残章吧")
                        --endif
                        udg_gudongA = 0
                    else
                        UnitAddItemById(u, 1227896131)
                        DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00你还没有收集齐两个A古董哦")
                    end
                else
                    DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00你还没有收集齐两个A古董哦")
                end
            end
        else
            DisplayTimedTextToPlayer(p, 0, 0, 15, "|CFF00FF00非鉴定师不能接此任务")
        end
    end
    if udg_jdds[i] >= 10 and udg_jddsbool[i] == false and Ce[i] == 4 then
        udg_jddsbool[i] = true
        if udg_zhangmen[i] == true then
        else
            SaveStr(YDHT, GetHandleId(p), GetHandleId(p), "〓鉴定大师〓" .. (LoadStr(YDHT, GetHandleId(p), GetHandleId(p)) or ""))
        end
        DisplayTimedTextToForce(bj_FORCE_ALL_PLAYERS, 15, "|CFF66FF00恭喜" .. (GetPlayerName(p) or "") .. "获得鉴定大师")
        SetPlayerName(p, "〓鉴定大师〓" .. (GetPlayerName(p) or ""))
    end
    u = nil
    p = nil
end

local function init()
    -- 初始化古董价格区间
    rs = CreateTrigger()
    TriggerRegisterTimerEventSingle(rs, 0.5)
    TriggerAddAction(rs, s5)
    -- 古董价格变动
    ss = CreateTrigger()
    TriggerRegisterTimerEventPeriodic(ss, 200.0)
    TriggerAddAction(ss, u5)
    -- 查询古董价格
    ts = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(ts, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    TriggerAddCondition(ts, Condition(w5))
    TriggerAddAction(ts, x5)
    -- 卖古董
    us = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(us, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    TriggerAddCondition(us, Condition(z5))
    TriggerAddAction(us, A5)
    vs = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(vs, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    TriggerAddCondition(vs, Condition(B5))
    TriggerAddAction(vs, b5)
    -- 收集古董
    vs = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(vs, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    TriggerAddCondition(vs, Condition(CollectGuDong_Conditions))
    TriggerAddAction(vs, CollectGuDong_Actions)
end
init()
