---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/16 12:59
---
--经验符
function oQ()
    return GetPlayerController(GetOwningPlayer(GetTriggerUnit())) == MAP_CONTROL_USER and GetItemTypeId(GetManipulatedItem()) == 1952807024
end
function pQ()
    AddHeroXP(udg_hero[1 + GetPlayerId(GetOwningPlayer(GetTriggerUnit()))], 200000, true)
end

local function init()
    -- 吃经验符
    kr = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(kr, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    TriggerAddCondition(kr, Condition(oQ))
    TriggerAddAction(kr, pQ)
end
init()