---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/15 21:41
---

local function init()
    -- 杀怪回血
    et.game:event '单位-杀死单位'(function(self, killer, killed)
        if killer:get_owner():is_player() and killer:get_owner().hero then
            local h = killer:get_owner().hero
            local hu = et.unit(h.handle)
            -- 没有枯荣禅功
            if not hu:has_ability(1093677914) then
                hu:set_life(hu:get_life() + h['杀怪回复'] + h['胆魄'] / 2000 * hu:get_max_life())
            end
        end
    end)

    --每秒回血回蓝
    et.loop(1000, function()
        for i = 1, 5 do
            local p = et.player(i)
            local h = p.hero
            if h then
                local hu = et.unit(h.handle)
                if p:is_hero() and not h:has_buff(1110454580) then
                    hu:set_life_percent(hu:get_life_percent() + h['医术'] / 2000 + 10 * hu:get_ability_level(1093682228) + guixihuixie[p.id])
                    if hu:has_item(1227895108) then
                        hu:set_life_percent(hu:get_life_percent() + 6)
                    end
                    hu:set_life(hu:get_life() + h['生命回复'])
                    hu:set_mana(hu:get_mana() + 0.3 * h['医术'] + h['法力回复'] + 5 * hu:get_ability_level(1093682228))
                end
            end
        end
    end)

    -- 攻击回复（伤害回复）
    et.game:event '单位-受攻击'(function(self, source, target)
        if target:is_hero() and target:get_owner():is_player() then
            if not target:has_ability(1093677914) then
                local h = target:get_owner().hero
                target:set_life(target:get_life() + h['伤害回复'] / 10 + h['胆魄'] / 1500 * hu:get_max_life())
            end
        end
    end)

    -- 伤害吸收
    et.game:event '单位-受到伤害'(function(self, source, target, damage)
        if target:is_hero() then
            local p = target:get_owner()
            local h = p.hero
            if not h then
                return
            end
            local r = (1 - math.min(h['伤害吸收'], 0.8)) * damage
            target:set_life(target:get_life() + math.min(h['伤害吸收'], 0.8) * damage)
            if target:has_buff(1110454340) and target:has_ability(1093678930) then
                target:set_life(target:get_life() + 0.3 * damage)
            end
            if target:has_item(1227897178) then
                if target:has_ability(1093677903) then
                    r = r / 3
                end
                if p:get_gold() >= r / 20 then
                    p:add_gold(math.floor(-r / 20))
                    target:set_life(math.min(target:get_life() + r, target:get_max_life()))
                else
                    target:set_life(math.min(target:get_life() + 5 * p:get_gold(), target:get_max_life()))
                    p:set_gold(0)
                end
            end
        end
    end)
end
init()