---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/16 12:58
---

local function init()
    -- 攻破城门
    et.game:event '单位-死亡' (function(self, killer, killed)
        if killed:get_id() == 1752003700 then
            ModifyGateBJ(1, Gt)
            et.wait(360 - 20 * et.player.countAlive(), function()
                ModifyGateBJ(0, Gt)
            end)
        end
    end)
end
init()