---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/29 0029 20:25
---



-- 按ESC查看人物属性
--[[
    去掉用丹数量
]]


local function init()
    et.game:event '玩家-按下ESC' (function(self, p)
        h = p.hero
        p:clear_messages()
        p:send_message("|cFFFF0000人物属性：")
        p:send_message("|cFFcc99ff〓〓〓〓〓〓〓〓〓〓〓")
        p:send_message("|cFF00FFFF暴击率 ：   " .. math.min(h['暴击率'], 100) .. "%")
        p:send_message("|cFF00FFFF暴击伤害 ：   " .. h['暴击伤害'] .. "%")
        p:send_message("|cFF00FFFF武功伤害加成 ：   " .. h['伤害加成'] .. "%")
        p:send_message("|cFF00FFFF伤害吸收 ：   " .. math.min(h['伤害吸收'], 80) .. "%")
        p:send_message("|cFFcc99ff〓〓〓〓〓〓〓〓〓〓〓")
        p:send_message("|cFF00FFFF根骨 ：   " .. h['根骨'])
        p:send_message("|cFF00FFFF悟性 ：   " .. h['悟性'])
        p:send_message("|cFF00FFFF经脉 ：   " .. h['经脉'])
        p:send_message("|cFF00FFFF福缘 ：   " .. h['福缘'])
        p:send_message("|cFF00FFFF胆魄 ：   " .. h['胆魄'])
        p:send_message("|cFF00FFFF医术 ：   " .. h['医术'])
        p:send_message("|cFFcc99ff〓〓〓〓〓〓〓〓〓〓〓")
        p:send_message("|cFF33FF00绝学领悟力：" .. h['绝学领悟'])
        p:send_message("|cFF33FF00修行：" .. h['历练'])
        p:send_message("|cFF33FF00武学修为：第" ..  h['武学修为'] .. "层")
        p:send_message("|cFF33FF00江湖声望：" .. h['声望'])
        p:send_message("|cFF33FF00守家积分：" .. h.def_point)
    end)

end

init()
