---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/16 12:56
---
--------武功效果系统开始------
function uC()
    return UnitHasBuffBJ(GetAttacker(), 1110454322)
end
function vC()
    local u = GetAttacker()
    if GetUnitState(u, UNIT_STATE_LIFE) <= 0.001 * GetUnitState(u, UNIT_STATE_MAX_LIFE) then
        SetWidgetLife(u, 1.0)
    else
        SetWidgetLife(u, GetUnitState(u, UNIT_STATE_LIFE) - 0.001 * GetUnitState(u, UNIT_STATE_MAX_LIFE))
    end
    u = nil
end
function xC()
    return UnitHasBuffBJ(GetAttacker(), 1112437615)
end
function yC()
    local u = GetAttacker()
    if GetUnitState(u, UNIT_STATE_LIFE) <= 0.003 * GetUnitState(u, UNIT_STATE_MAX_LIFE) then
        SetWidgetLife(u, 1.0)
    else
        SetWidgetLife(u, GetUnitState(u, UNIT_STATE_LIFE) - 0.003 * GetUnitState(u, UNIT_STATE_MAX_LIFE))
    end
    u = nil
end
function AC()
    return IsUnitAliveBJ(GetFilterUnit()) and (UnitHasBuffBJ(GetFilterUnit(), 1111847784) or UnitHasBuffBJ(GetFilterUnit(), 1110454602) or UnitHasBuffBJ(GetFilterUnit(), 1110454323) or UnitHasBuffBJ(GetFilterUnit(), 1113813609) or UnitHasBuffBJ(GetFilterUnit(), 1110454324) or UnitHasBuffBJ(GetFilterUnit(), 1110454342) or UnitHasBuffBJ(GetFilterUnit(), 1110454343))
end
function aC()
    local loc = GetUnitLoc(GetEnumUnit())
    local loc2 = nil
    if UnitHasBuffBJ(GetEnumUnit(), 1111847784) then
        if GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) <= 0.001 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE) then
            SetWidgetLife(GetEnumUnit(), 1.0)
        else
            SetUnitState(GetEnumUnit(), UNIT_STATE_LIFE, GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) - 0.001 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE))
        end
    end
    if UnitHasBuffBJ(GetEnumUnit(), 1110454602) then
        if GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) <= 0.003 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE) then
            SetWidgetLife(GetEnumUnit(), 1.0)
        else
            SetUnitState(GetEnumUnit(), UNIT_STATE_LIFE, GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) - 0.003 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE))
        end
    end
    if UnitHasBuffBJ(GetEnumUnit(), 1110454323) then
        if GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) <= 0.002 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE) then
            SetWidgetLife(GetEnumUnit(), 1.0)
        else
            SetUnitState(GetEnumUnit(), UNIT_STATE_LIFE, GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) - 0.002 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE))
        end
    end
    if UnitHasBuffBJ(GetEnumUnit(), 1113813609) then
        loc2 = pu(loc, 256.0, GetRandomReal(0, 360.0))
        IssuePointOrderByIdLoc(GetEnumUnit(), 851986, loc2)
        RemoveLocation(loc2)
    end
    if UnitHasBuffBJ(GetEnumUnit(), 1110454324) then
        if GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) <= 0.003 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE) then
            SetWidgetLife(GetEnumUnit(), 1.0)
        else
            SetUnitState(GetEnumUnit(), UNIT_STATE_LIFE, GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) - 0.003 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE))
        end
    end
    if UnitHasBuffBJ(GetEnumUnit(), 1110454342) then
        if ModuloInteger(GetUnitPointValue(GetEnumUnit()), 10) ~= 0 then
            if GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) <= 0.01 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE) then
                SetWidgetLife(GetEnumUnit(), 1.0)
            else
                SetUnitState(GetEnumUnit(), UNIT_STATE_LIFE, GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) - 0.01 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE))
            end
        else
            if GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) <= 0.03 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE) then
                SetWidgetLife(GetEnumUnit(), 1.0)
            else
                SetUnitState(GetEnumUnit(), UNIT_STATE_LIFE, GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) - 0.03 * GetUnitState(GetEnumUnit(), UNIT_STATE_MAX_LIFE))
            end
        end
        CreateTextTagLocBJ("脑神丹效果", loc, 60.0, 12.0, 65.0, 55.0, 42.0, 0)
        Nw(3.0, bj_lastCreatedTextTag)
        SetTextTagVelocityBJ(bj_lastCreatedTextTag, 100.0, 90)
    end
    if UnitHasBuffBJ(GetEnumUnit(), 1110454343) then
        --if(GetUnitState(GetEnumUnit(),UNIT_STATE_LIFE)<=0.03*GetUnitState(GetEnumUnit(),UNIT_STATE_MAX_LIFE))then
        --	call SetWidgetLife(GetEnumUnit(),1.)
        --else
        SetUnitState(GetEnumUnit(), UNIT_STATE_LIFE, GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE) - 0.03 * GetUnitState(GetEnumUnit(), UNIT_STATE_LIFE))
        --endif
        CreateTextTagLocBJ("化尸粉效果", loc, 60.0, 12.0, 65.0, 55.0, 42.0, 0)
        Nw(3.0, bj_lastCreatedTextTag)
        SetTextTagVelocityBJ(bj_lastCreatedTextTag, 100.0, 90)
    end
    RemoveLocation(loc)
    loc = nil
    loc2 = nil
end
--每秒钟做一次
function BC()
    ForGroupBJ(wv(bj_mapInitialPlayableArea, Condition(AC)), aC)
end
local function init()
    pk = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(pk, EVENT_PLAYER_UNIT_ATTACKED)
    TriggerAddCondition(pk, Condition(uC))
    TriggerAddAction(pk, vC)
    qk = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(qk, EVENT_PLAYER_UNIT_ATTACKED)
    TriggerAddCondition(qk, Condition(xC))
    TriggerAddAction(qk, yC)
    rk = CreateTrigger()
    TriggerRegisterTimerEventPeriodic(rk, 1.0)
    TriggerAddAction(rk, BC)
end
init()