---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/30 13:04
---
function WuXueJingYao(u)
    local p = u:get_owner()
    local i = p.id
    local j = GetRandomInt(1, 8)
    local level = u:get_ability_level(I7[(i - 1) * 20 + j])
    if I7[(i - 1) * 20 + j] ~= 1093678418 then
        u:set_ability_level(u:get_ability_level() + 1)
        if u.get_ability_level(u, I7[(i - 1) * 20 + j]) == level then
            u:add_item(1227899219)
            p:send_message("|cFFFFCC00随机到九重或无法升重的技能，使用武学精要失败")
        else
            p:send_message("|cFFFFCC00恭喜技能" .. (jass.GetAbilityName(I7[(i - 1) * 20 + j]) or "") .. "升重")
        end
    else
        u:add_item(1227899219)
        p:send_message("|cFFFFCC00随机到凌波微步，使用武学精要失败")
    end
end

local function init()
    -- FIXME 使用武学精要（目前有BUG）
    et.game:event '单位-使用物品'(function(self, u, item)
        if u:get_owner():is_player() and jass.GetItemTypeId(item) == 1227899219 then
            WuXueJingYao(u)
        end
    end)
end

init()