---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/29 0029 21:04
---

local function init()
    --游戏胜利
    et.game:event '单位-杀死单位' (function(self, killer, killed)
        if base.string2id(killed.id) == 1851942003 then
            force.send_message("|CFFFF00B2决战江湖1.55的游戏总评分：" .. ae .. "分（通关）")
            force.send_message("|CFFFF00B2恭喜你们通关，游戏将在1分钟后结束\n游戏专区论坛：jzjhbbs.uuu9.com\n游戏交流QQ群：159030768 369925013\n关注武侠，让决战江湖走得更远，期待你的参与，详情请在专区论坛查询")
            local r, g, b, a = 40, 70, 100, 70
            et.loop(40, function(t)
                if not de then
                    t:remove()
                end
                if r <= 10 then
                    r = 100
                else
                    r = r - 10
                end
                if g <= 10 then
                    g = 100
                else
                    g = g - 10
                end
                if b <= 10 then
                    b = 100
                else
                    b = b - 10
                end
                if a <= 10 then
                    a = 70
                else
                    a = a - 10
                end
                for i = 1, et.player.countAlive() do
                    local p = et.player(i)
                    local h = p.hero
                    local u = et.unit(h.handle)
                    if h.bj_lastCreatedTextTag then
                        jass.DestroyTextTag(h.bj_lastCreatedTextTag)
                    end
                    h.bj_lastCreatedTextTag = u:create_tag("武林盟主", 11, 100, r, g, b, a)
                end
            end)
            et.wait(60 * 1000, function()
                force.victory()
            end)
        end
    end)

    --游戏失败
    local u = et.unit(udg_ZhengPaiWL)
    u:event '单位-死亡' (function(self, killer, killed)
        force.send_message("|CFFFF00B2决战江湖1.55的游戏总评分：" .. ae .. "分（战败）")
        force.fail()
    end)

end
init()
