---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/29 0029 21:04
---

function hy()
    return GetUnitTypeId(GetTriggerUnit()) == 1851942003
end
--是否达到胜利条件
function IsVictory()
    if de == false then
        FlushChildHashtable(YDHT, GetHandleId(GetExpiredTimer()))
        DestroyTimer(GetExpiredTimer())
    else
        if LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251) <= 10.0 then
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251, 100.0)
        else
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251) - 10.0)
        end
        if LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706) <= 10.0 then
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706, 100.0)
        else
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706) - 10.0)
        end
        if LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710) <= 0.1 then
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710, 100.0)
        else
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710) - 10.0)
        end
        if LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754) <= 0.0 then
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754, 70.0)
        else
            SaveReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754) - 10.0)
        end
        SaveInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558, 1)
        if udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] ~= nil then
            DestroyTextTag(ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)])
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951, GetUnitLoc(udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)]))
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584, pu(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951), 150.0, 110.0))
            CreateTextTagLocBJ("武林盟主", LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584), 100.0, 11.0, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584))
            ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] = bj_lastCreatedTextTag
        end
        SaveInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558, LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558) + 1)
        if udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] ~= nil then
            DestroyTextTag(ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)])
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951, GetUnitLoc(udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)]))
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584, pu(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951), 150.0, 110.0))
            CreateTextTagLocBJ("武林盟主", LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584), 100.0, 11.0, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584))
            ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] = bj_lastCreatedTextTag
        end
        SaveInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558, LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558) + 1)
        if udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] ~= nil then
            DestroyTextTag(ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)])
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951, GetUnitLoc(udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)]))
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584, pu(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951), 150.0, 110.0))
            CreateTextTagLocBJ("武林盟主", LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584), 100.0, 11.0, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584))
            ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] = bj_lastCreatedTextTag
        end
        SaveInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558, LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558) + 1)
        if udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] ~= nil then
            DestroyTextTag(ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)])
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951, GetUnitLoc(udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)]))
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584, pu(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951), 150.0, 110.0))
            CreateTextTagLocBJ("武林盟主", LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584), 100.0, 11.0, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584))
            ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] = bj_lastCreatedTextTag
        end
        SaveInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558, LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558) + 1)
        if udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] ~= nil then
            DestroyTextTag(ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)])
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951, GetUnitLoc(udg_hero[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)]))
            SaveLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584, pu(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951), 150.0, 110.0))
            CreateTextTagLocBJ("武林盟主", LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584), 100.0, 11.0, LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1587459251), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1676716706), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1559655710), LoadReal(YDHT, GetHandleId(GetExpiredTimer()), -1663695754))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), 1585647951))
            RemoveLocation(LoadLocationHandle(YDHT, GetHandleId(GetExpiredTimer()), -1925439584))
            ee[LoadInteger(YDHT, GetHandleId(GetExpiredTimer()), -1449975558)] = bj_lastCreatedTextTag
        end
    end
end
--胜利动作
function Victory()
    local ky
    local id = GetHandleId(GetTriggeringTrigger())
    local cx = LoadInteger(YDHT, id, -807506826)
    local i = 0
    cx = cx + 3
    SaveInteger(YDHT, id, -807506826, cx)
    SaveInteger(YDHT, id, -320330265, cx)
    i = 1
    for _ in _loop_() do
        if i >= 6 then break end
        udg_MeiJuJiFen[i] = udg_MeiJuJiFen[i] + ae // 50
        YDWE_PreloadSL_Set(Player(i - 1), "总积分", 1, udg_MeiJuJiFen[i])
        YDWE_PreloadSL_Save(Player(i - 1), "JueZhan", "JiangHu" .. (I2S(i) or ""), 1)
        i = i + 1
    end
    DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|CFFFF00B2决战江湖1.55的游戏总评分：" .. (I2S(ae) or "") .. "分（通关）")
    DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|CFFFF00B2恭喜你们通关，游戏将在2分钟后结束\n游戏专区论坛：jzjhbbs.uuu9.com\n游戏交流QQ群：159030768 369925013\n关注武侠，让决战江湖走得更远，期待你的参与，详情请在专区论坛查询")
    de = true
    SaveReal(YDHT, id * cx, -1587459251, 40.0)
    SaveReal(YDHT, id * cx, -1676716706, 70.0)
    SaveReal(YDHT, id * cx, -1559655710, 100.0)
    SaveReal(YDHT, id * cx, -1663695754, 70.0)
    ky = CreateTimer()
    SaveReal(YDHT, GetHandleId(ky), -1587459251, LoadReal(YDHT, id * cx, -1587459251))
    SaveReal(YDHT, GetHandleId(ky), -1676716706, LoadReal(YDHT, id * cx, -1676716706))
    SaveReal(YDHT, GetHandleId(ky), -1559655710, LoadReal(YDHT, id * cx, -1559655710))
    SaveReal(YDHT, GetHandleId(ky), -1663695754, LoadReal(YDHT, id * cx, -1663695754))
    TimerStart(ky, 0.04, true, IsVictory)
    YDWEPolledWaitNull(60.0)
    SaveInteger(YDHT, id, -320330265, cx)
    DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|CFFFF00B2决战江湖1.55的游戏总评分：" .. (I2S(ae) or "") .. "分（通关）")
    DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|CFFFF00B2恭喜你们通关，游戏将在1分钟后结束\n游戏专区论坛：jzjhbbs.uuu9.com\n游戏交流QQ群：159030768 369925013\n关注武侠，让决战江湖走得更远，期待你的参与，详情请在专区论坛查询")
    YDWEPolledWaitNull(60.0)
    SaveInteger(YDHT, id, -320330265, cx)
    CustomVictoryBJ(Player(0), true, true)
    CustomVictoryBJ(Player(1), true, true)
    CustomVictoryBJ(Player(2), true, true)
    CustomVictoryBJ(Player(3), true, true)
    CustomVictoryBJ(Player(4), true, true)
    FlushChildHashtable(YDHT, id * cx)
    ky = nil
end
--失败动作
function Lose()
    local i = 0
    DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|CFFFF00B2决战江湖1.55的游戏总评分：" .. (I2S(ae) or "") .. "分（战败）")
    i = 1
    for _ in _loop_() do
        if i >= 6 then break end
        udg_MeiJuJiFen[i] = udg_MeiJuJiFen[i] + ae // 100
        YDWE_PreloadSL_Set(Player(i - 1), "总积分", 1, udg_MeiJuJiFen[i])
        YDWE_PreloadSL_Save(Player(i - 1), "JueZhan", "JiangHu" .. (I2S(i) or ""), 1)
        i = i + 1
    end
    CustomDefeatBJ(Player(0), "没有能守护住正派武林!")
    CustomDefeatBJ(Player(1), "没有能守护住正派武林!")
    CustomDefeatBJ(Player(2), "没有能守护住正派武林!")
    CustomDefeatBJ(Player(3), "没有能守护住正派武林!")
    CustomDefeatBJ(Player(4), "没有能守护住正派武林!")
end

local function init()
    et.game:event '单位-杀死单位' (function(self, killer, killed)
        if base.string2id(killed.id) == 1851942003 then

        end
    end)
    -- 击杀最终BOSS游戏胜利
    hi = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(hi, EVENT_PLAYER_UNIT_DEATH)
    TriggerAddCondition(hi, Condition(hy))
    TriggerAddAction(hi, Victory)
    -- 老家灭了游戏失败
    ii = CreateTrigger()
    TriggerRegisterUnitEvent(ii, udg_ZhengPaiWL, EVENT_UNIT_DEATH)
    TriggerAddAction(ii, Lose)
end
init()
