---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/10/31 17:11
---


local function init()
    --爆炸
    et.game:event '单位-死亡'(function(self, killer, killed)
        if killer:has_ability(1093681749) then
            et.effect.add_to_point("war3mapImported\\ChaosExplosion.mdl", killed:get_point()):destroy()
            local group = et.selector():in_range(killed:get_point(), 300):add_filter(function(ut)
                return ut:is_enemy(killed) and ut:is_alive()
            end)            :get()
            for _, v in pairs(group) do
                v:set_life(v:get_life() - 200 * v:get_level())
            end

        end
    end)

    et.game:event '单位-受攻击'(function(self, source, target)
        -- 流星
        if source:has_ability(1093681753) and commonutil.random_int(1, 70) <= 5 then
            local last = source:get_owner():create_unit(1697656919, source:get_point())
            last:add_ability(1093681754)
            last:issue_order(852183)
            last:set_lifetime(15)
            last:show(false)
        end
        -- 冰缓
        if source:has_ability(1093681968) and commonutil.random_int(1, 70) <= 5 then
            local last = source:get_owner():create_unit(1697656918, source:get_point())
            last:set_lifetime(15)
        end
    end)
end
init()