---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/30 12:43
---

local function point_exchange(u, it, id1, num, id2)
    local p = u:get_owner()
    local i = p.id
    local h = p.hero
    if jass.GetItemTypeId(it) == id1 then
        if h.def_point >= num then
            h.def_point = h.def_point - num
            if is_in(id1, { 1227896403, 1227896404, 1227896402, 1227896405, 1227896401 }) then
                local last_item = u.add_item(id2)
                p:send_message("|CFF34FF00获得" .. GetItemName(last_item))
            elseif id1 == 1227896400 then
                p:add_lumber(20 - udg_nandu * 2)
                p:send_message("|CFF34FF00获得珍稀币+" .. (20 - udg_nandu * 2))
            elseif id1 == 1227896399 then
                p:add_gold(5000 - udg_nandu * 50)
                p:send_message("|CFF34FF00获得金钱+" .. (5000 - udg_nandu * 500))
            elseif id1 == 1227899184 then
                local ht = h.handle
                local last_item = ht:add_item(id2)
                p:send_message("|CFF34FF00获得" .. GetItemName(last_item))
            end
            p:send_message("|cFF00CCff当前剩余守家积分：" .. h.def_point)
        else
            p:send_message("|cFFFFCC00守家积分不足")
        end
    end
end

local function reputation_exchange(u, it, id1, num, id2)
    local p = u:get_owner()
    local h = p.hero
    if jass.GetItemTypeId(it) == id1 then
        if h.reputation >= num then
            h.reputation = h.reputation - num
            local last_item = u.add_item(id2)
            p:send_message("|CFF34FF00获得" .. GetItemName(last_item))
            p:send_message("|cFF00CCff当前剩余江湖声望：" .. h.reputation)
        else
            p:send_message("|cFFFFCC00江湖声望不足")
        end
    end
end

local function init()

    et.game:event '单位-捡起物品'(function(self, u, item)
        local l = { 1227896399, 1227899184, 1227896403, 1227896404, 1227896402, 1227896405, 1227896400, 1227896401, }
        -- 积分换物品
        if u:get_owner():is_player() and is_in(jass.GetItemTypeId(item), l) then
            point_exchange(u, item, 1227896399, 20, 300)
            point_exchange(u, item, 1227899184, 50, 1227895892)
            point_exchange(u, item, 1227896403, 200, YaoCao[GetRandomInt(1, 12)])
            point_exchange(u, item, 1227896404, 100, 1227895374)
            point_exchange(u, item, 1227896402, 300, 1227896395)
            point_exchange(u, item, 1227896405, 600, 1227895372)
            point_exchange(u, item, 1227896400, 100, 5)
            point_exchange(u, item, 1227896401, 200, 1227896398)
        end
        -- 声望换物品
        l = { 1227899215, 1227899216, 1227899217, 1227899218, }
        if u:get_owner():is_player() and is_in(jass.GetItemTypeId(item), l) then
            reputation_exchange(u, item, 1227899215, 200, 1227896395)
            reputation_exchange(u, item, 1227899216, 4000, 1227896919)
            reputation_exchange(u, item, 1227899217, 2000, 1227899219)
            reputation_exchange(u, item, 1227899218, 1000, udg_canzhang[GetRandomInt(1, 10)])
        end
    end)

end

init()