---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/15 19:49
---
udg_MaxDamage = {0, 0, 0, 0, 0}

--- @param mb j_multiboard
--- @param column number
--- @param row number
--- @param value string
function update_multiboard_item_value(mb, column, row, value)
    local row_count = jass.MultiboardGetRowCount(mb)
    local column_count = jass.MultiboardGetColumnCount(mb)
    if row > row_count or column > column_count then
        return
    end
    board_item = jass.MultiboardGetItem(mb, row - 1, column - 1)
    jass.MultiboardSetItemValue(board_item, value)
    jass.MultiboardReleaseItem(board_item)
end


-- 保留多少位小数，默认为2位
local function get_precise_decimal(nNum, n)
    if type(nNum) ~= "number" then
        return nNum;
    end

    n = n or 2;
    n = math.floor(n)
    local fmt = '%.' .. n .. 'f'
    local nRet = tonumber(string.format(fmt, nNum))

    return nRet;
end

-- 将数字转化为字符串，并用万和亿进行简化
local function get_num_string(num)
    local s
    if num < 10000.0 then
        s = '' .. get_precise_decimal(num)
    elseif num < 100000000.0 then
        s = '' .. get_precise_decimal(num / 10000) .. "万"
    elseif num / 10000.0 < 100000000.0 then
        s = '' .. get_precise_decimal(num / 10000 / 10000) .. "亿"
    elseif num / 100000000.0 < 100000000.0 then
        s = '' .. get_precise_decimal(num / 10000 / 10000 / 10000) .. "万亿"
    else
        s = '' .. get_precise_decimal(num / 10000 / 10000 / 10000 / 10000) .. "亿亿"
    end
    return s
end

local function init()
    -- 首次显示系统窗口信息
    et.wait(10 * 1000, function()
        CreateMultiboardBJ(5, 20, "系统窗口")
        MultiboardSetItemsStyle(bj_lastCreatedMultiboard, true, false)
        MultiboardSetItemsWidth(bj_lastCreatedMultiboard, 0.07)
        for i = 1, 5 do
            local s = get_num_string(udg_MaxDamage[i])
            MultiboardSetTitleText(bj_lastCreatedMultiboard, "|cFFFFCC33萌萌哒系统窗口")
            update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i - 3, "|c00FF0080" .. (GetPlayerName(Player(i - 1)) or ""))
            update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i - 3, "|c0000FF00" .. "等级：" .. (I2S(GetUnitLevel(udg_hero[i])) or ""))
            update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i - 3, "|cFF00CCFF" .. (udg_menpainame[udg_runamen[i]] or ""))
            update_multiboard_item_value(bj_lastCreatedMultiboard, 4, 4 * i - 3, "|cFFFF6600" .. "最高伤害：" .. (s or ""))
            if Ce[i] == 1 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99炼丹师")
            elseif Ce[i] == 2 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99锻造师")
            elseif Ce[i] == 3 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99兵器师")
            elseif Ce[i] == 4 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99鉴定师")
            elseif Ce[i] == 5 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99练气师")
            elseif Ce[i] == 6 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99寻宝师")
            elseif Ce[i] == 7 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99丫鬟")
            elseif Ce[i] == 8 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99精武师")
            else
                update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99未选择")
            end
            if I7[20 * (i - 1) + 1] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 1]) or ""))
            end
            if I7[20 * (i - 1) + 2] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 2]) or ""))
            end
            if I7[20 * (i - 1) + 3] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 3]) or ""))
            end
            if I7[20 * (i - 1) + 4] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 4, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 4]) or ""))
            end
            if I7[20 * (i - 1) + 5] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 5]) or ""))
            end
            if I7[20 * (i - 1) + 6] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 6]) or ""))
            end
            if I7[20 * (i - 1) + 7] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 7]) or ""))
            end
            if I7[20 * (i - 1) + 8] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 4, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 8]) or ""))
            end
            if I7[20 * (i - 1) + 9] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 9]) or ""))
            end
            if I7[20 * (i - 1) + 10] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 10]) or ""))
            end
            if I7[20 * (i - 1) + 11] ~= 1095067243 then
                update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 11]) or ""))
            end
        end
        MultiboardDisplay(bj_lastCreatedMultiboard, true)

        -- 刷新系统窗口信息

        et.loop(4 * 1000, function()
            for i = 1, 5 do
                local s = get_num_string(udg_MaxDamage[i])
                MultiboardSetTitleText(bj_lastCreatedMultiboard, "|cFFFFCC33萌萌哒系统窗口")
                update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i - 3, "|c00FF0080" .. (GetPlayerName(Player(i - 1)) or ""))
                update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i - 3, "|c0000FF00" .. "等级：" .. (I2S(GetUnitLevel(udg_hero[i])) or ""))
                update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i - 3, "|cFF00CCFF" .. (udg_menpainame[udg_runamen[i]] or ""))
                update_multiboard_item_value(bj_lastCreatedMultiboard, 4, 4 * i - 3, "|cFFFF6600" .. "最高伤害：" .. (s or ""))
                if Ce[i] == 1 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99炼丹师")
                elseif Ce[i] == 2 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99锻造师")
                elseif Ce[i] == 3 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99兵器师")
                elseif Ce[i] == 4 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99鉴定师")
                elseif Ce[i] == 5 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99练气师")
                elseif Ce[i] == 6 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99寻宝师")
                elseif Ce[i] == 7 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99丫鬟")
                elseif Ce[i] == 8 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99精武师")
                else
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 5, 4 * i - 3, "|c00FFEE99未选择")
                end
                if I7[20 * (i - 1) + 1] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 1]) or ""))
                end
                if I7[20 * (i - 1) + 2] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 2]) or ""))
                end
                if I7[20 * (i - 1) + 3] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 3]) or ""))
                end
                if I7[20 * (i - 1) + 4] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 4, 4 * i - 2, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 4]) or ""))
                end
                if I7[20 * (i - 1) + 5] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 5]) or ""))
                end
                if I7[20 * (i - 1) + 6] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 6]) or ""))
                end
                if I7[20 * (i - 1) + 7] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 7]) or ""))
                end
                if I7[20 * (i - 1) + 8] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 4, 4 * i - 1, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 8]) or ""))
                end
                if I7[20 * (i - 1) + 9] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 1, 4 * i, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 9]) or ""))
                end
                if I7[20 * (i - 1) + 10] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 2, 4 * i, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 10]) or ""))
                end
                if I7[20 * (i - 1) + 11] ~= 1095067243 then
                    update_multiboard_item_value(bj_lastCreatedMultiboard, 3, 4 * i, "|c0000FF00" .. (GetObjectName(I7[20 * (i - 1) + 11]) or ""))
                end
            end
        end)
    end)

    --- 计算玩家最大伤害
    --- @param source unit
    --- @param target unit
    --- @param damage number
    et.game:event '单位-受到伤害' (function(self, source, target, damage)
        if target:get_owner():is_player() or damage < source:get_owner():get_max_damage() then
            return
        end
        source:get_owner():set_max_damage(damage)
    end)
end
--init()