---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/30 13:36
---

--结拜系统

-- 结拜兄弟的队列
local brother_queue = {}

local function init()
    -- 买黄纸
    et.game:event '单位-捡起物品'(function(self, u, item)
        if jass.GetItemTypeId(item) == 1227894832 then
            u:add_item(1227896153)
            u:add_item(1227896153)
        end
    end)

    -- 烧黄纸
    et.game:event '单位-使用物品'(function(self, u, item)
        if jass.GetItemTypeId(item) == 1227896153 then
            local p = u:get_owner()
            local h = p.hero
            if h.burned_paper then
                p:send_message("|cffff0000你已经使用过黄纸了，还是等等另外一个人的响应吧")
                u:add_item(1227896153)
            else
                h.burned_paper = true
                table.insert(brother_queue, h)
                if #brother_queue == 2 then
                    h.brother = brother_queue[1]
                    table.remove(brother_queue)
                    table.remove(brother_queue)
                    p:send_message("|cffff66ff恭喜" .. p:get_name() .. "和" .. h.brother:get_owner():get_name() .. "结拜为兄弟")
                else
                    p:send_message("|cffff66ff使用成功，等待另外一位玩家与你结拜....")
                end
            end
        end
    end)

    -- 跳到结拜兄弟/夫妻处
    et.game:event '玩家-聊天' (function(self, p, s)
        if s == '~' then
            local h = p.hero
            if h.brother then
                local hu = h.handle
                local hbu = h.brother.handle
                hu:set_point(hbu:get_point())
                p:set_camera(hu:get_point())
            end
        end
    end)


end
init()
