---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/29 0029 20:40
---


local function init()
    -- 玩家英雄阵亡
    et.game:event '单位-死亡'(function(self, killer, killed)
        if killed:is_hero() and killed:get_owner():is_player() then
            local p = killed:get_owner()
            local revive_time = ge[p.id] and 7 or 15
            et.timerdialog(revive_time, "复活倒计时:")
            GroupRemoveUnit(k9, killed.handle)
            GroupRemoveUnit(j9, killed.handle)
            GroupRemoveUnit(s9, killed.handle)
            GroupRemoveUnit(r9, killed.handle)
            N8[p.id] = 0
            if killed:has_item(1227895379) or killed:has_item(1227895373) or killed:has_item(1227895377) or killed:has_item(1227895378) or killed:has_item(1227895376) then
                if Ce[p.id] ~= 3 then
                    p:send_message("|cFFff0000养武消失了")
                end
            end
            -- 玩家英雄复活
            et.wait(revive_time * 1000, function()
                Q4 = GetRectCenter(He)
                jass.ReviveHeroLoc(killed.handle, Q4, true)
                p:set_camera(et.get_rect_center(He))
                RemoveLocation(Q4)
                he[p.id] = false
                local hu = et.unit(p.hero.handle)
                if killed:has_item(1227895379) or killed:has_item(1227895373) or killed:has_item(1227895377) or killed:has_item(1227895378) or killed:has_item(1227895376) then
                    if Ce[p.id] ~= 3 then
                        jass.RemoveItem(hu:fetch_item(1227895379))
                        jass.RemoveItem(hu:fetch_item(1227895373))
                        jass.RemoveItem(hu:fetch_item(1227895377))
                        jass.RemoveItem(hu:fetch_item(1227895378))
                        jass.RemoveItem(hu:fetch_item(1227895376))
                    end
                end
                if hu:has_ability(1093677877) then
                    local level = hu.get_ability_level(1093677877)
                    hu:remove_ability(1093677877)
                    hu:set_ability_level(1093677876, level)
                end
                AddCharacterABuff(hu.handle, p.hero.char_a)
                AddCharacterBBuff(hu.handle, p.hero.char_b)
            end)
        end
    end)
end

init()
