---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/16 12:46
---

--主机选择模式
function Trig_____________u_Func002C()
    return GetPlayerController(Player(0)) == MAP_CONTROL_USER and GetPlayerSlotState(Player(0)) == PLAYER_SLOT_STATE_PLAYING
end
function ChooseMoShi()
    DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|cff00FF40主机开始选择游戏模式")
    if GetPlayerController(Player(0)) == MAP_CONTROL_USER and GetPlayerSlotState(Player(0)) == PLAYER_SLOT_STATE_PLAYING then -- INLINED!!
        DialogClear(udg_index)
        DialogSetMessage(udg_index, "请选择游戏模式")
        udg_index0 = DialogAddButtonBJ(udg_index, "|cFF00CC00普通模式")
        udg_index1 = DialogAddButtonBJ(udg_index, "|cFFCC0066特殊事件模式")
        udg_index2 = DialogAddButtonBJ(udg_index, "|cFFFF6600生存模式")
        udg_index3 = DialogAddButtonBJ(udg_index, "|cFF6600FF快速通关模式")
        DialogDisplayBJ(true, udg_index, Player(0))
    end
end
function ChooseMoShi_Action()
    if GetClickedButton() == udg_index0 then
        DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|cff00FFFF主机选择了普通模式")
        game.config.mode = 'normal'
    end
    if GetClickedButton() == udg_index1 then
        DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|cff00FFFF主机选择了特殊事件模式")
        game.config.mode = 'special'
    end
    if GetClickedButton() == udg_index2 then
        DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|cff00FFFF主机选择了生存模式")
        game.config.mode = 'survive'
    end
    if GetClickedButton() == udg_index3 then
        DisplayTextToForce(bj_FORCE_ALL_PLAYERS, "|cff00FFFF主机选择了快速通关模式")
        game.config.mode = 'fast'
    end
end

local function init()
    t = CreateTrigger()
    TriggerRegisterDialogEvent(t, udg_index)
    TriggerAddAction(t, ChooseMoShi_Action)
end
init()