---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/29 0029 20:45
---
-- 设置游戏难度和经验获得率的函数
local function set_difficulty_and_exp_rate(difficulty)
    et.player(7):set_tech(1378889777, difficulty * 10)
    et.player(13):set_tech(1378889777, difficulty * 10)
    et.player(16):set_tech(1378889777, difficulty * 10)
    udg_nandu = difficulty
    for i = 1, 5 do
        jass.SetPlayerHandicapXP(et.player(i).handle, 2 - 0.2 * difficulty)
    end
end
function choose_difficulty()
    force.send_message("|cff00FF40主机开始选择游戏难度")
    if et.player(1):is_player() then
        local button_list = {}
        if udg_nandu <= 0 then
            table.insert(button_list, "|cFF00CC00初入江湖")
        end
        if udg_nandu <= 0 then
            table.insert(button_list, "|cFFCC0066牛刀小试")
        end
        if udg_nandu <= 0 then
            table.insert(button_list, "|cFFFF6600登堂入室")
        end
        if udg_nandu <= 0 then
            table.insert(button_list, "|cFF0041FF炉火纯青")
        end
        if udg_nandu <= 0 then
            table.insert(button_list, "|cff1fbf00华山论剑")
        end
        if udg_nandu <= 0 then
            table.insert(button_list, "|cFFFF0000决战江湖")
        end
        local d = et.dialog.create(et.player(1), "请选择游戏难度", button_list)
        local button_map = {
            ["|cFF00CC00初入江湖"] = 0,
            ["|cFFCC0066牛刀小试"] = 1,
            ["|cFFFF6600登堂入室"] = 2,
            ["|cFF0041FF炉火纯青"] = 3,
            ["|cff1fbf00华山论剑"] = 4,
            ["|cFFFF0000决战江湖"] = 5,
        }
        for k, v in pairs(button_map) do
            et.event_register(d.buttons[k], '对话框-按钮点击')(function(self, dg, pl)
                d:clear_and_destroy()
                force.send_message("|cff00FFFF主机选择了难度" .. k)
                set_difficulty_and_exp_rate(v)
                if v == 5 then
                    force.send_message("|cff00FFFF该模式下进攻怪具有|cFFFF0000抽血术")
                end
            end)
        end
    end
end

local function init()
    -- up提升游戏难度
    et.player(1):event '玩家-聊天'(function(self, p, s)
        if s:sub(1, 2) == 'up' then
            --非特殊事件模式、非生存模式
            if (is_in(game.config.mode, { 'normal', 'fast' })) then
                local i
                if tonumber(s:sub(3, 5)) == 0 then
                    i = 10
                else
                    i = tonumber(s:sub(3, 5)) * 10
                end
                local level = et.player(13):get_tech(1378889777)
                if level == 50 then
                    p:send_message("当前已为最高难度了")
                else
                    if level + i >= 50 then
                        i = 50 - level
                    end
                    et.player(7):add_tech(1378889777, i)
                    et.player(13):add_tech(1378889777, i)
                    et.player(15):add_tech(1378889777, i)
                    udg_nandu = udg_nandu + i // 10
                    force.send_message("玩家1输入“up”提高了游戏难度，目前游戏难度为" .. udg_nandu)
                    if udg_nandu == 5 then
                        force.send_message("|cff00FFFF该模式下进攻怪具有|cFFFF0000抽血术")
                    end
                end
            end
        end
    end)
end
init()