---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/16 12:46
---

--- 主机选择模式 第五波还有一次选择模式的时间
function select_game_mode()
    local button_map = {
        ["|cFF00CC00普通模式"] = 'normal',
        ["|cFFCC0066特殊事件模式"] = 'special',
        ["|cFFFF6600生存模式"] = 'survive',
        ["|cFF6600FF快速通关模式"] = 'fast',
    }
    local button_list = table.keys(button_map)
    local d = et.dialog.create(et.player(1), "|cff00FF40主机开始选择游戏模式", button_list)

    et.game:event_register '对话框-按钮点击'(function(self, b, dg, pl)
        for k, v in pairs(button_map) do
            if b == d.buttons[k] then
                force.send_message("|cff00FFFF主机选择了" .. k)
                game.config.mode = v
                dg:clear_and_destroy()
            end
        end
    end)

end

et.wait(2000, function()
    select_game_mode()
end)