---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/15 21:35
---
--遗忘武功
local function do_forget(p, id)
    local h = p.hero
    local hu = et.unit(h.handle)
    if id == 1093677902 and hu:has_buff(1112504171) then
        p:send_message("|CFFFF9933" .. jass.GetObjectName(id) .. "施展期间不能遗忘！！！")
    else
        if et.lni.internal[id] then
            local itl = et.lni.internal[id]
            h['伤害加成'] = h['伤害加成'] - itl['伤害加成']
            jass.SetHeroAgi(hu, jass.GetHeroAgi(hu) - itl['内力'])
            h['暴击率'] = h['暴击率'] - itl['暴击率']
            h['绝学领悟'] = h['绝学领悟'] - itl['绝学领悟']
            h['伤害吸收'] = h['伤害吸收'] - itl['伤害吸收']
        end
        p:send_message("|CFFFF9933成功遗忘技能：" .. jass.GetObjectName(id))
        hu:remove_ability(id)
        if id == 1093677904 then
            hu:remove_ability(1093677901)
        end
        if id == 1093677908 then
            hu:remove_ability(1093682242)
        end
        -- TODO 替换掉udg_zhemei
        if id == 1093677634 then
            udg_zhemei[p.id] = 0
        end
        if id == 1095067243 then
            hu:remove_item()
        end
        jass.RemoveItem(h['伴侣']:fetch_item(1227896395))
    end
end

-- 鸟的'遗忘技能'技能
--   param u 玩家的鸟
local function forget_ability(u)
    local p = u:get_owner()
    local h = p.hero
    local button_list = {}
    if u:has_item(1227896395) or h.forgetable then
        -- 生成按钮清单
        for _, v in pairs(h['武功']) do
            local id = v.ability_id
            table.insert(button_list, jass.GetObjectName(id))
        end
        table.insert(button_list, '取消')
        local d = et.dialog.create(p, "请选择遗忘的武功（遗忘后无法找回）！", button_list)

        -- 向按钮注册事件
        et.game:event '对话框-按钮点击' (function(self, b, dg, pl)
            for _, v in pairs(h['武功']) do
                local id = v.ability_id
                if b == d.buttons[jass.GetObjectName(id)] then
                    do_forget(p, id)
                    d:clear_and_destroy()
                end
            end
            if b == d.buttons['取消'] then
                d:clear_and_destroy()
            end
        end)
    else
        p:send_message("|cffff0000遗忘武功需要消耗道具遗忘之石！")
    end
end
local function init()
    -- 遗忘武功

    et.game:event '单位-技能生效'(function(self, u, id, target)
        if id == 1093678417 then
            forget_ability(u)
        end
    end)
end
init()