---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/15 21:00
---

local holy_monster_list = { udg_qinglong, udg_baihu, udg_zhuque, udg_xuanwu, gg_unit_n00M_0131 }
local aggressive_points = {}
local passive_points = {}

local function init()

    --将地图上初始所有单位加入单位组
    et.wait(2000, function()
        -- 中立敌对
        local aggressive = et.selector():of_player(et.player(13)):get()
        for _, v in ipairs(aggressive) do
            aggressive_points[v.handle] = v:get_point()
        end
        local passive = et.selector():of_player(et.player(16)):get()
        for _, v in pairs(passive) do
            passive_points[v.handle] = v:get_point()
        end
    end)

    --怪物死后重新刷怪
    et.game:event '单位-死亡'(function(self, killer, killed)
        if is_in(killed:get_owner(), { et.player(13), et.player(16) }) then
            --圣兽死后不刷新
            if not is_in(killed.handle, holy_monster_list) then
                if aggressive_points[killed.handle] then
                    et.wait((180 - 10 * et.player.countAlive()) * killed:get_point_value(), function()
                        et.player(13):create_unit(killed:get_type_id(), aggressive_points[killed.handle], 270)
                    end)
                end
                if passive_points[killed.handle] then
                    et.wait((180 - 10 * et.player.countAlive()) * killed:get_point_value(), function()
                        et.player(16):create_unit(killed:get_type_id(), passive_points[killed.handle], 270)
                    end)
                end
            end
        end
    end)

end
init()