---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/16 12:52
---

function qT()
    return GetPlayerController(GetOwningPlayer(GetTriggerUnit())) == MAP_CONTROL_USER and (GetItemTypeId(GetManipulatedItem()) == 1227899471 or GetItemTypeId(GetManipulatedItem()) == 1227896659)
end
function rT()
    if GetItemTypeId(GetManipulatedItem()) == 1227896659 then
        famous_num = 5
        DisplayTimedTextToForce(bj_FORCE_ALL_PLAYERS, 30.0, "|cff00ffff有玩家开始预约名门挑战，本波进攻怪物将会增加名门高手，大家要小心应付了！")
    end
    if GetItemTypeId(GetManipulatedItem()) == 1227899471 then
        famous_num = 0
        DisplayTimedTextToForce(bj_FORCE_ALL_PLAYERS, 30.0, "|cff00ffff有玩家取消了预约名门挑战，下波进攻怪物将不会增加名门高手，大家要小心应付了！")
    end
end

local function init()
    -- 预约名门和取消预约
    Gs = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(Gs, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    TriggerAddCondition(Gs, Condition(qT))
    TriggerAddAction(Gs, rT)
end
init()