---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/1 9:07
---

--魔教救人
function MoJiaoJiuRen_1()
    SetUnitPosition(GetEnumUnit(), -910, 750)
end
function MoJiaoJiuRen()

    ForGroupBJ(YDWEGetUnitsInRectOfPlayerNull(udg_jail, Player(6)), MoJiaoJiuRen_1)
end

local function init()
    et.wait(1000.0, function()
        force.send_message("|CFFCCFF00魔教潜入监狱救走了被抓住的敌人")
            local function in_rect(u)
                return u:getX() < jass
            end
            local group = et.selector():add_filter():get()
    end)

end
init()