---
--- Generated by EmmyLua(https://github.com/EmmyLua
--- Created by G_Seinfeld.
--- DateTime: 2018/11/17 0017 11:24
---

-- 生成伴侣的ini文件

require('war3.id')

-- 字符串分割
local function split(str, p)
    local rt = {}
    str:gsub('[^' .. p .. ']+', function(w)
        table.insert(rt, w)
    end)
    return rt
end

local function main()
    local file = io.open('generator/source.txt', 'r')
    local dest = io.open('lni/table/pellet.ini', 'a+')
    local dest2 = io.open('generator/dest2.txt', 'a+')
    local tab = {}

    for line in file:lines() do
        local strs = split(line, ',')
        local item_id = base.id2string(strs[1])
        local yishu = strs[2]
        local yin = strs[3]
        local yang = strs[4]
        local inducer = strs[5]
        YaoCao = { 1227896646, --车前草
                   1227896647, --过路黄
                   1227896645, --金钱草
                   1227896630, --金银花
                   1227896631, --锦灯笼
                   1227896632, --苦地丁
                   1227896633, --款冬花
                   1227896642, --奇异果
                   1227896641, --升丹
                   1227896643, --土当归
                   1227896644, --五加皮
                   1227896648, --紫花兰
        }
        dest:write("['" .. item_id .. "']", '\n')
        dest:write("'item_id' = '", item_id, "'\n")
        dest:write("'医术' = ", yishu, '\n')
        dest:write("'yin' = ", yin, '\n')
        dest:write("'yang' = ", yang, '\n')
        dest2:write(item_id, '\n')
        --dest:write("'inducer' = ", load(inducer)(), '\n')
        fun = assert(load('return ' .. inducer))
        print(fun)
        dest:write("'inducer' = '", base.id2string(fun()), "'\n")
    end
    file:close()
end

main()