---
--- Generated by EmmyLua(https://github.com/EmmyLua
--- Created by G_Seinfeld.
--- DateTime: 2018/11/17 0017 11:24
---

-- 生成伴侣的ini文件

require('util.id')

-- 字符串分割
local function split(str, p)
    local rt = {}
    str:gsub('[^' .. p .. ']+', function(w)
        table.insert(rt, w)
    end)
    return rt
end

local function main()
    local file = io.open('generator/source.txt', 'r')
    local dest = io.open('lni/table/partner.ini', 'a+')
    for line in file:lines() do
        local strs = split(line, ',')
        local item_id = strs[2]
        local unit_id = strs[3]
        local gg = strs[4]
        local wx = strs[5]
        local jm = strs[6]
        local fy = strs[7]
        local dp = strs[8]
        local ys = strs[9]
        print(base.id2string(item_id), base.id2string(unit_id), gg, wx, jm, fy, dp, ys)
        dest:write("['']", '\n')
        dest:write("'item_id' = '", base.id2string(item_id), "'\n")
        dest:write("'unit_id' = '", base.id2string(unit_id), "'\n")
        dest:write("'根骨' = ", gg, '\n')
        dest:write("'悟性' = ", wx, '\n')
        dest:write("'经脉' = ", jm, '\n')
        dest:write("'福缘' = ", fy, '\n')
        dest:write("'胆魄' = ", dp, '\n')
        dest:write("'医术' = ", ys, '\n')
    end
    file:close()
end

main()