---
--- Generated by EmmyLua(https://github.com/EmmyLua
--- Created by G_Seinfeld.
--- DateTime: 2018/11/17 0017 11:24
---

-- 生成伴侣的ini文件

require('war3.id')

-- 字符串分割
local function split(str, p)
    local rt = {}
    str:gsub('[^' .. p .. ']+', function(w)
        table.insert(rt, w)
    end)
    return rt
end

local function main()
    local file = io.open('generator/source.txt', 'r')
    local dest = io.open('lni/table/herb.ini', 'a+')
    local dest2 = io.open('generator/dest2.txt', 'a+')
    local tab = {}

    for line in file:lines() do
        local strs = split(line, ',')
        local item_id = base.id2string(strs[1])
        local name = strs[2]
        local yin = strs[3]
        local yang = strs[4]

        dest:write("['" .. name .. "']", '\n')
        dest:write("'item_id' = '", item_id, "'\n")
        dest:write("'yin' = ", yin, '\n')
        dest:write("'yang' = ", yang, '\n')
    end
    file:close()
end

main()