---1852798818
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/4 0004 21:55
---

--- 副本2 崆峒山
local set = require 'util.collection.set'

--- {木桩、野兽}：{星云戒指、胆魄丹、福缘丹}
drop_item({ 1701212014, 1852798818 }, { [1227895113] = 3, [1227895365] = 3, [1227895368] = 3 })

--- {唐文亮}：{精钢剑、精钢护腕、破军帽、破军鞋}
drop_item(1851942007, { [1227895116] = 25, [1227895117] = 25, [1227895121] = 25, [1227895122] = 25 })

--- {关能}：{七星扇、七星戒指、七星锦服}
drop_item(1852076663, { [1227895118] = 33, [1227895120] = 33, [1227895119] = 34 })

--- {李莫愁}：{四门刀法、冰魄银针}
drop_item(1702258030, { [1227895621] = 50, [1227895626] = 50 })

--- {木灵子}：{七伤拳、斗转星移}
drop_item(1700884333, { [1227895628] = 50, [1227895382] = 50 })

--- {狄云}：{唐诗剑法、连城剑法}
drop_item(1852007777, { [1227895603] = 50, [1227895627] = 50 })

--- 有玩家进入副本2
enter_instance_listener {
    num = 2,
    item_id = 1227895638,
    name = '崆峒山',
    gold = 300,
    practice = 1,
    practice_point = et.point(-5456.0, -2960.0),
    enter_point = et.point(-15264.0, 5312.0),
    mystery_point = et.point(-12672.0, 6592.0),
    mystery_set = set:new { 1702258030, 1700884333, 1852007777 },
    rare_drop_set = set:new { 1227895109, 1227895379, 1227895111, 1227895371 },
    npc_set = set:new { 1865429071, 1865429059 },
    npc_point_set = set:new {
        et.point(-14160.0, 6240.0),
        et.point(-14064.0, 7216.0),
        et.point(-13808.0, 8416.0),
        et.point(-11408.0, 8016.0),
        et.point(-11376.0, 5952.0),
        et.point(-13008.0, 5920.0),
    },
}

et.game:event '单位-死亡'(function(self, killer, killed)
    if et.rect.j_rect(rect_instance_two):contains_unit(killer) and commonutil.random(0, 100) <= 2 then
        if instance_info[2].rare_drop_id then
            local x, y = killed:get_point():get()
            et.item:new(instance_info[2].rare_drop_id, x, y)
        end
    end
end)

--- @param source unit 被接近的单位
--- @param approach unit 接近的单位
et.game:event '单位-被接近'(function(self, source, approach)
    if source:get_type_id() == base.string2id('o00C') and approach:is_hero() then
        approach:get_owner():dummy_use_ability(1697656880, approach:get_point(), 1093677875, 852164, nil, 3)
    end
    if source:get_type_id() == base.string2id('o00O') and approach:is_hero() then
        approach:get_owner():dummy_use_ability(1697656880, approach:get_point(), 1093678673, 852066, nil, 3)
    end
end)

