---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/5 10:02
---

--- 野外副本

--- {野猪首领}：{护身符、布衣}
drop_item(1852924467, { [1227895347] = 50, [1227895346] = 50 })

--- {豺狼}：{车前草}
drop_item(1852272243, { [base.string2id('I07F')] = 8 })

--- {江南水怪}：{过路黄}
drop_item(1752654196, { [base.string2id('I07G')] = 8 })

--- {林朝英}：{江湖武功、江湖内功}
drop_item(1852076403, { [wild_kungfus] = 50, [wild_internals] = 50 }, { [base.string2id('I07A')] = 100 })

--- {古墓弟子}：{金币}、{五加皮}
drop_item(1852076406, { [1227895897] = 25 }, { [base.string2id('I07D')] = 15 })

--- {极恶领主}：{经验符}、{土当归}
drop_item(1852206966, { [1952807024] = 100 }, { [base.string2id('I07C')] = 100 })

--- {扫地神僧}：{绝世武功}
drop_item(1853059688, { [outstanding_kungfus] = 100 })

--- {黄裳}：{绝世内功}
drop_item(1752395892, { [outstanding_internals] = 100 })

--- {矮人}：{决战·魁}
drop_item(1752328550, { [1227896921] = 7 })

--- {矮子王}：{江湖·忠}
drop_item(1215130471, { [1227896918] = 100 })

--- {牛妖}：{残章}
drop_item(1852467042, { [remnant_chapters] = 12 })

--- {渣小庸}：{江湖·义、决战·恶、决战·霸}
drop_item(1852207203, { [1227896920] = 33, [1227896922] = 33, [1227897136] = 34 })

---门派叛徒和武林恶徒

--- 边境掉落

