---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/2 9:43
---

local ability = {}

local mt = {}
ability.__index = mt

mt.type='ability'

return ability