---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local alliancetype = {}

local mt = {}
alliancetype.__index = mt

mt.type = 'alliancetype'
mt.name = ''

function alliancetype.init()
	local alliancetype_names={}
	for i = 1, #alliancetype_names do
		local al = {}
		al.name = alliancetype_names[i]
		setmetatable(al, alliancetype)
		table.insert(alliancetype, al)
	end
end

return alliancetype
