---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local blendmode = {}

local mt = {}
blendmode.__index = mt

mt.type = 'blendmode'
mt.name = ''

function blendmode.init()
	local blendmode_names={}
	for i = 1, #blendmode_names do
		local bl = {}
		bl.name = blendmode_names[i]
		setmetatable(bl, blendmode)
		table.insert(blendmode, bl)
	end
end

return blendmode