---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/7 16:58
---

local common_util = require 'jass.util.common_util'
local boolexpr = {}

local mt = {}
boolexpr.__index = mt

mt.type = 'boolexpr'

function mt:_and(br)
    return boolexpr.create(function()
        return self.fun() and br.fun()
    end)
end

function mt:_or(br)
    return boolexpr.create(function()
        return self.fun() or br.fun()
    end)
end

function mt:_not()
    return boolexpr.create(function()
        return not self.fun()
    end)
end

function mt:destroy()
    boolexpr[self.handle_id] = nil
end

function boolexpr.create(fun)
    local b = setmetatable({}, boolexpr)
    b.fun = fun
    b.handle_id = common_util.generate_handle_id()
    boolexpr[b.handle_id] = b
    return b
end

return boolexpr