---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/18 0018 10:59
---

local common_util = require 'jass.util.common_util'
local button = {}
button.all_buttons = {}

local mt = {}
button.__index = mt
mt.type = 'button'

mt.text = ''
mt.hotkey = 'Y'
mt.is_quit = false
mt.do_score_screen = false

function button.create(text, hotkey, is_quit, do_score_screen)
    local b = setmetatable({}, button)
    b.handle_id = common_util.generate_handle_id()
    b.text = text
    b.hotkey = hotkey
    b.is_quit = is_quit
    b.do_score_screen = do_score_screen
    button.all_buttons[b.handle_id] = b
    return b

end

return button