---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/5 11:47
---

local destructable = {}

local mt = {}
destructable.__index = mt

mt.type = 'destructable'

mt.id = 0
mt.x = 0
mt.y = 0

function mt:get_id()
    return self.id
end

function mt:get_x()
    return self.x
end

function mt:get_y()
    return self.y
end

return destructable

