---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local dialogevent = {}

local mt = {}
dialogevent.__index = mt

mt.type = 'dialogevent'
mt.name = ''

function dialogevent.init()
	local dialogevent_names={}
	for i = 1, #dialogevent_names do
		local di = {}
		di.name = dialogevent_names[i]
		setmetatable(di, dialogevent)
		table.insert(dialogevent, di)
	end
end
