---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local effecttype = {}

local mt = {}
effecttype.__index = mt

mt.type = 'effecttype'
mt.name = ''

function effecttype.init()
	local effecttype_names={}
	for i = 1, #effecttype_names do
		local ef = {}
		ef.name = effecttype_names[i]
		setmetatable(ef, effecttype)
		table.insert(effecttype, ef)
	end
end
