---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local fgamestate = {}

local mt = {}
fgamestate.__index = mt

mt.type = 'fgamestate'
mt.name = ''

function fgamestate.init()
	local fgamestate_names={'GAME_STATE_TIME_OF_DAY'}
	for i = 2, #fgamestate_names+1 do
		local fg = {}
		fg.name = fgamestate_names[i-1]
		setmetatable(fg, fgamestate)
		fgamestate[i] = fg
	end
end

return fgamestate