---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/3 0003 21:58
---

local common_util = require 'jass.util.common_util'
local player = require('jass.type.player')

local force = {}
force.filter_player = nil
force.enum_player = nil

local mt = {}
force.__index = mt

mt.type = 'force'

function mt:add_player(p)
    self.players[p.handle_id] = p
end

function mt:destroy()
    force[self.handle_id] = nil
end

function mt:remove(p)
    self.players[p.handle_id] = nil
end

function mt:clear()
    for k, _ in pairs(self) do
        self[k] = nil
    end
end

function mt:enum_players(base_condition, filter, count)
    local counter = 0
    for _, v in pairs(player.all_players) do
        if not base_condition or base_condition(v) then
            force.filter_player = v
            if not filter or filter.fun() then
                if count and counter >= count then
                    return
                end
                self:add_player(v)
                counter = counter + 1
            end
        end
    end
end

function mt:foreach(callback)
    for _, v in pairs(self.players) do
        force.enum_player = v
        callback()
    end
end

function force.create()
    local f = setmetatable({}, force)
    f.handle_id = common_util.generate_handle_id()
    force[f.handle_id] = f
    f.players = {}
    return f
end

return force