---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local igamestate = {}

local mt = {}
igamestate.__index = mt

mt.type = 'igamestate'
mt.name = ''

function igamestate.init()
	local igamestate_names={}
	for i = 1, #igamestate_names do
		local ig = {}
		ig.name = igamestate_names[i]
		setmetatable(ig, igamestate)
		table.insert(igamestate, ig)
	end
end
