---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local mapdensity = {}

local mt = {}
mapdensity.__index = mt

mt.type = 'mapdensity'
mt.name = ''

function mapdensity.init()
	local mapdensity_names={}
	for i = 1, #mapdensity_names do
		local ma = {}
		ma.name = mapdensity_names[i]
		setmetatable(ma, mapdensity)
		table.insert(mapdensity, ma)
	end
end

return mapdensity