---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local mapvisibility = {}

local mt = {}
mapvisibility.__index = mt

mt.type = 'mapvisibility'
mt.name = ''

function mapvisibility.init()
	local mapvisibility_names={}
	for i = 1, #mapvisibility_names do
		local ma = {}
		ma.name = mapvisibility_names[i]
		setmetatable(ma, mapvisibility)
		table.insert(mapvisibility, ma)
	end
end

return mapvisibility