---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/5 11:23
---

local playerstate = {}

local mt = {}
playerstate.__index = mt

mt.type = 'playerstate'
mt.name = ''

function playerstate.init()
    playerstate_names = {
        'PLAYER_STATE_GAME_RESULT',
        'PLAYER_STATE_RESOURCE_GOLD',
        'PLAYER_STATE_RESOURCE_LUMBER',
        'PLAYER_STATE_RESOURCE_HERO_TOKENS',
        'PLAYER_STATE_RESOURCE_FOOD_CAP',
        'PLAYER_STATE_RESOURCE_FOOD_USED',
        'PLAYER_STATE_FOOD_CAP_CEILING',
        'PLAYER_STATE_GIVES_BOUNTY',
        'PLAYER_STATE_ALLIED_VICTORY',
        'PLAYER_STATE_PLACED',
        'PLAYER_STATE_OBSERVER_ON_DEATH',
        'PLAYER_STATE_OBSERVER',
        'PLAYER_STATE_UNFOLLOWABLE',
    }
    for i = 1, #playerstate_names do
        local ps = {}
        ps.name = playerstate_names[i]
        setmetatable(ps, playerstate)
        table.insert(playerstate, ps)
    end

end

return playerstate