---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local playergameresult = {}

local mt = {}
playergameresult.__index = mt

mt.type = 'playergameresult'
mt.name = ''

function playergameresult.init()
	local playergameresult_names={}
	for i = 1, #playergameresult_names do
		local pl = {}
		pl.name = playergameresult_names[i]
		setmetatable(pl, playergameresult)
		table.insert(playergameresult, pl)
	end
end

return playergameresult