---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local common_util = require 'jass.util.common_util'
local playerunitevent = {}

local mt = {}
playerunitevent.__index = mt

mt.type = 'playerunitevent'
mt.name = ''
function playerunitevent.init()
    local playerunitevent_names = {
        'EVENT_PLAYER_UNIT_ATTACKED',
        'EVENT_PLAYER_UNIT_RESCUED',
        'EVENT_PLAYER_UNIT_DEATH',
        'EVENT_PLAYER_UNIT_DECAY',
        'EVENT_PLAYER_UNIT_DETECTED',
        'EVENT_PLAYER_UNIT_HIDDEN',
        'EVENT_PLAYER_UNIT_SELECTED',
        'EVENT_PLAYER_UNIT_DESELECTED',
        'EVENT_PLAYER_UNIT_CONSTRUCT_START',
        'EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL',
        'EVENT_PLAYER_UNIT_CONSTRUCT_FINISH',
        'EVENT_PLAYER_UNIT_UPGRADE_START',
        'EVENT_PLAYER_UNIT_UPGRADE_CANCEL',
        'EVENT_PLAYER_UNIT_UPGRADE_FINISH',
        'EVENT_PLAYER_UNIT_TRAIN_START',
        'EVENT_PLAYER_UNIT_TRAIN_CANCEL',
        'EVENT_PLAYER_UNIT_TRAIN_FINISH',
        'EVENT_PLAYER_UNIT_RESEARCH_START',
        'EVENT_PLAYER_UNIT_RESEARCH_CANCEL',
        'EVENT_PLAYER_UNIT_RESEARCH_FINISH',
        'EVENT_PLAYER_UNIT_ISSUED_ORDER',
        'EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER',
        'EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER',
        'EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER',
        'EVENT_PLAYER_HERO_LEVEL',
        'EVENT_PLAYER_HERO_SKILL',
        'EVENT_PLAYER_HERO_REVIVABLE',
        'EVENT_PLAYER_HERO_REVIVE_START',
        'EVENT_PLAYER_HERO_REVIVE_CANCEL',
        'EVENT_PLAYER_HERO_REVIVE_FINISH',
        'EVENT_PLAYER_UNIT_SUMMON',
        'EVENT_PLAYER_UNIT_DROP_ITEM',
        'EVENT_PLAYER_UNIT_PICKUP_ITEM',
        'EVENT_PLAYER_UNIT_USE_ITEM',
        'EVENT_PLAYER_UNIT_LOADED',
    }
    local playerunitevent_names_new = {
        'EVENT_PLAYER_UNIT_SELL',
        'EVENT_PLAYER_UNIT_CHANGE_OWNER',
        'EVENT_PLAYER_UNIT_SELL_ITEM',
        'EVENT_PLAYER_UNIT_SPELL_CHANNEL',
        'EVENT_PLAYER_UNIT_SPELL_CAST',
        'EVENT_PLAYER_UNIT_SPELL_EFFECT',
        'EVENT_PLAYER_UNIT_SPELL_FINISH',
        'EVENT_PLAYER_UNIT_SPELL_ENDCAST',
        'EVENT_PLAYER_UNIT_PAWN_ITEM',
    }
    for i = 18, #playerunitevent_names + 17 do
        local pl = {}
        pl.name = playerunitevent_names[i - 17]
        pl.handle_id = common_util.generate_handle_id()
        setmetatable(pl, playerunitevent)
        playerunitevent[i] = pl
    end
    for i = 269, #playerunitevent_names_new + 268 do
        local pl = {}
        pl.name = playerunitevent_names_new[i - 268]
        pl.handle_id = common_util.generate_handle_id()
        setmetatable(pl, playerunitevent)
        playerunitevent[i] = pl
    end
end

return playerunitevent