---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/1 11:31
---

local common_util = require 'jass.util.common_util'
local player = {}
setmetatable(player, player)
local MAX_PLAYER_NUM = 16

local mt = {}
player.__index = mt

-- 是否为观察者
mt.observer = false
mt.id = 0
mt.type = 'player'
mt.name = '玩家1'

function mt:is_ally(p)
    return common_util.is_in_table(p, self.allies)
end

function mt:is_enemy(p)
    return not is_ally(p)
end

function mt:is_in_force(f)
    return common_util.is_in_table(p, f)
end

function mt:is_observer()
    return self.observer
end

function mt:get_id()
    return self.id
end

function mt:get_unit_count()
    local counter = 0
    for k, v in pairs(self.units) do
        counter = counter + 1
    end
    return counter
end

function mt:get_name()
    return self.name
end

function mt:set_alliance(p, alliance_type)
    if type(self.allies) == 'table' then
        --FIXME 是否需要分类别
        table.insert(self.allies, p)
    end
end

function mt:set_state(state, value)
    p[state] = value
end

function player:__call(i)
    return player[i]
end

function player.get_local()
    if player.native then
        return player.native
    else
        return player[1]
    end
end

function player.init()
    for i = 1, MAX_PLAYER_NUM do
        local p = {}
        p.handle_id = common_util.generate_handle_id()
        p.id = i - 1
        p.units = {}
        setmetatable(p, player)
        table.insert(player, p)
        p.allies = {}
        p.name = '玩家' .. i
    end
    player.native = player[1]
end

return player