---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local playerscore = {}

local mt = {}
playerscore.__index = mt

mt.type = 'playerscore'
mt.name = ''

function playerscore.init()
	local playerscore_names={}
	for i = 1, #playerscore_names do
		local pl = {}
		pl.name = playerscore_names[i]
		setmetatable(pl, playerscore)
		table.insert(playerscore, pl)
	end
end

return playerscore