---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/5 11:23
---

local playerstate = {}

local mt = {}
playerstate.__index = mt

mt.type = 'playerstate'
mt.name = ''

function playerstate.init()
    local playerstate_names = {
        'PLAYER_STATE_GAME_RESULT',
        'PLAYER_STATE_RESOURCE_GOLD',
        'PLAYER_STATE_RESOURCE_LUMBER',
        'PLAYER_STATE_RESOURCE_HERO_TOKENS',
        'PLAYER_STATE_RESOURCE_FOOD_CAP',
        'PLAYER_STATE_RESOURCE_FOOD_USED',
        'PLAYER_STATE_FOOD_CAP_CEILING',
        'PLAYER_STATE_GIVES_BOUNTY',
        'PLAYER_STATE_ALLIED_VICTORY',
        'PLAYER_STATE_PLACED',
        'PLAYER_STATE_OBSERVER_ON_DEATH',
        'PLAYER_STATE_OBSERVER',
        'PLAYER_STATE_UNFOLLOWABLE',
        'PLAYER_STATE_GOLD_UPKEEP_RATE',
        'PLAYER_STATE_LUMBER_UPKEEP_RATE',
        'PLAYER_STATE_GOLD_GATHERED',
        'PLAYER_STATE_LUMBER_GATHERED',
        'PLAYER_STATE_NO_CREEP_SLEEP',
    }
    for i = 0, #playerstate_names - 1 do
        local ps = {}
        ps.name = playerstate_names[i+1]
        setmetatable(ps, playerstate)
        playerstate[i] = ps
    end
    playerstate[25] = playerstate[17]

end

return playerstate