---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local playerunitevent = {}

local mt = {}
playerunitevent.__index = mt

mt.type = 'playerunitevent'
mt.name = ''

function playerunitevent.init()
	local playerunitevent_names={}
	for i = 1, #playerunitevent_names do
		local pl = {}
		pl.name = playerunitevent_names[i]
		setmetatable(pl, playerunitevent)
		table.insert(playerunitevent, pl)
	end
end
