---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/5 13:44
---

local playerslotstate = {}

local mt = {}
playerslotstate.__index = mt

mt.type = 'playerslotstate'
mt.name = ''

function playerslotstate.init()
    local playerslotstate_names = {

    }
    for i = 1, #playerslotstate_names do
        local pss = {
            'PLAYER_SLOT_STATE_EMPTY',
            'PLAYER_SLOT_STATE_PLAYING',
            'PLAYER_SLOT_STATE_LEFT',
        }
        pss.name = playerslotstate_names[i]
        setmetatable(pss, playerslotstate)
        table.insert(playerslotstate, pss)
    end
end

return playerslotstate

