---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local raritycontrol = {}

local mt = {}
raritycontrol.__index = mt

mt.type = 'raritycontrol'
mt.name = ''

function raritycontrol.init()
	local raritycontrol_names={}
	for i = 1, #raritycontrol_names do
		local ra = {}
		ra.name = raritycontrol_names[i]
		setmetatable(ra, raritycontrol)
		table.insert(raritycontrol, ra)
	end
end

return raritycontrol