---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/8 9:10
---

local common_util = require 'jass.util.common_util'
local region = {}

local mt = {}
region.__index = mt

mt.type='region'

function mt:add_rect(rt)
    self.cells[rt.handle_id] = rt
end

function mt:remove_rect(rt)
    self.cells[rt.handle_id] = nil
end

function region.create()
    local r = setmetatable({}, region)
    r.handle_id = common_util.generate_handle_id()
    region[r.handle_id] = r
    r.cells = {}
    return r
end

return region