---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local startlocprio = {}

local mt = {}
startlocprio.__index = mt

mt.type = 'startlocprio'
mt.name = ''

function startlocprio.init()
	local startlocprio_names={}
	for i = 1, #startlocprio_names do
		local st = {}
		st.name = startlocprio_names[i]
		setmetatable(st, startlocprio)
		table.insert(startlocprio, st)
	end
end

return startlocprio