---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/18 0018 10:37
---

local common_util = require 'jass.util.common_util'
local texttag = {}
texttag.all_texttags = {}

local mt = {}
texttag.__index = mt
mt.type = 'texttag'
mt.text = ''
mt.height = 0
mt.pos = {0, 0, 0}
mt.color = {128, 128, 128, 128}
mt.velocity = {10, 10}
mt.shown = true
mt.suspended = false
mt.permanent = false
mt.age = 0
mt.life_span = 3
mt.fade_point = 50

function mt:set_text(text, height)
    self.text = text
    self.height = height
end

function mt:set_pos(x, y, z)
    self.pos = {x, y, z}
end

function mt:set_color(r, g, b, a)
    self.color = {r, g, b, a}
end

function mt:set_velocity(x_vel, y_vel)
    self.velocity = {x_vel, y_vel}
end

function mt:show(flag)
    self.shown = flag
end

function mt:suspend(flag)
    self.suspended = flag
end

function mt:set_permanent(flag)
    self.permanent = flag
end

function mt:set_age(age)
    self.age = age
end

function mt:set_life_span(life_span)
    self.life_span = life_span
end

function mt:set_fade_point(fade_point)
    self.fade_point = fade_point
end

function mt:destroy()
    texttag.all_texttags[self.handle_id] = nil
end

function texttag.create()
    local tt = setmetatable({}, texttag)
    tt.handle_id = common_util.generate_handle_id()
    texttag.all_texttags[tt.handle_id] = tt
    return tt
end

return texttag