---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lhing17.
--- DateTime: 2018/11/2 9:44
---

local common_util = require 'jass.util.common_util'
local event = require 'jass.type.event'
local triggercondition = require 'jass.type.triggercondition'
local triggeraction = require 'jass.type.triggeraction'
local trigger = {}
trigger.all_triggers = {}

-- 正在触发的触发器
trigger.triggering = nil

--- @class j_trigger
local mt = {}
trigger.__index = mt

mt.type = 'trigger'
mt.enabled = true

function trigger:__tostring()
    return 'trigger'..self.handle_id
end

function mt:destroy()
    trigger.all_triggers[self.handle_id] = nil
end

function mt:enable()
    self.enabled = true
end

function mt:is_enabled()
    return self.enabled
end

function mt:disable()
    self.enabled = false
end

function mt:register_player_event(p, pe)
    local e = event.create_player_event(p, pe)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:register_player_chat_event(p, message, exact)
    local e = event.create_player_chat_event(p, message, exact)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:register_player_unit_event(p, pue, filter)
    local e = event.create_player_unit_event(p, pue, filter)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:register_unit_event(u, ue, filter)
    local e = event.create_unit_event(u, ue, filter)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:register_timer_expire_event(t)
    local e = event.create_timer_expire_event(t)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:register_game_state_event(state, opcode, value)
    local e = event.create_game_state_event(state, opcode, value)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:register_enter_region(r, filter)
    local e = event.create_enter_region_event(r, filter)
    self.registered_events[e.handle_id] = e
    return e
end
function mt:register_leave_region(r, filter)
    local e = event.create_leave_region_event(r, filter)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:register_dialog_event(d)
    local e = event.create_dialog_event(d)
    self.registered_events[e.handle_id] = e
    return e
end

--- @param b j_button
--- @return j_event
function mt:register_dialog_button_event(b)
    local e = event.create_dialog_button_event(b)
    self.registered_events[e.handle_id] = e
    return e
end

function mt:evaluate()
    local flag = true
    for _, v in pairs(self.conditions) do
        if v.fun then
            flag = flag and v.boolexpr.fun()
        end
    end
    return flag
end

function mt:execute()
    for _, v in pairs(self.actions) do
        v.fun()
    end
end

function mt:add_condition(filter)
    local tc = triggercondition.create(filter)
    self.conditions[tc.handle_id] = tc
    return tc
end

function mt:remove_condition(tc)
    self.conditions[tc.handle_id] = nil
end

function mt:clear_conditions()
    for k, _ in pairs(self.conditions) do
        self.conditions[k] = nil
    end
end

function mt:add_action(fun)
    local ta = triggeraction.create(fun)
    self.actions[ta.handle_id] = ta
    return ta
end

function mt:remove_action(ta)
    self.actions[ta.handle_id] = nil
end

function mt:clear_actions()
    for k, _ in pairs(self.actions) do
        self.actions[k] = nil
    end
end

function trigger.create()
    local t = setmetatable({}, trigger)
    t.handle_id = common_util.generate_handle_id()
    trigger.all_triggers[t.handle_id] = t
    t.registered_events = {}
    t.conditions = {}
    t.actions = {}
    return t
end

return trigger