---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/9 8:42
---
local common_util = require 'jass.util.common_util'
local triggeraction = {}
triggeraction.all_actions = {}

local mt = {}
triggeraction.__index = mt

mt.type='triggeraction'

function triggeraction.create(fun)
    local ta = setmetatable({}, triggeraction)
    ta.handle_id= common_util.generate_handle_id()
    triggeraction.all_actions[ta.handle_id] = ta
    ta.fun = fun
    return ta
end

return triggeraction