---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/8 14:28
---

local common_util = require 'jass.util.common_util'
local triggercondition = {}
triggercondition.all_conditions = {}

local mt = {}
triggercondition.__index = mt

mt.type='triggercondition'

function triggercondition.create(filter)
    local tc = setmetatable({}, triggercondition)
    tc.handle_id = common_util.generate_handle_id()
    triggercondition.all_conditions[tc.handle_id] = tc
    triggercondition.boolexpr = filter
    return tc
end

return triggercondition