---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/1 11:30
---


local common_util = require 'jass.util.common_util'
local unit = {}
unit.all_units = {}
unit.removed_units = {}

local mt = {}
unit.__index = mt

mt.type = 'unit'

-- 是否存活 alive dead removed
mt.status = 'alive'




function mt:die()
    self.status = 'dead'
end

function mt:remove()
    self.status = 'removed'
    unit.all_units[self.handle_id] = nil
    unit.removed_units[self.handle_id] = self
end

function unit:__tostring()
    return self.handle_id .. ', ' .. self.type .. ', ' .. self.id .. ', ' .. self.x .. ', ' .. self.y
end

function unit.create(p, unitid, x, y, face)
    local u = {}
    setmetatable(u, unit)
    u.owner = p
    u.id = unitid
    u.handle_id = common_util.generate_handle_id()
    u.x = x
    u.y = y
    u.face = face
    unit.all_units[u.handle_id] = u
    return u
end

return unit