---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/5 12:59
---

local unitstate = {}

local mt = {}
unitstate.__index = mt

mt.type = 'unitstate'

function unitstate.init()
    local unitstate_names = {
        'UNIT_STATE_LIFE',
        'UNIT_STATE_MAX_LIFE',
        'UNIT_STATE_MANA',
        'UNIT_STATE_MAX_MANA',
    }
    for i = 0, #unitstate_names - 1 do
        local us = {}
        us.name = unitstate_names[i + 1]
        setmetatable(us, unitstate)
        unitstate[i] = us
    end


end

return unitstate