---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/5 14:04
---

local version = {}

local mt = {}
version.__index = mt

mt.type = 'version'
mt.name = ''

function version.init()
    local version_names = {
        'VERSION_REIGN_OF_CHAOS',
        'VERSION_FROZEN_THRONE',
    }
    for i = 1, #version_names do
        local v = {}
        v.name = version_names[i]
        setmetatable(v, version)
        table.insert(version, v)
    end
end

return version
