---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local volumegroup = {}

local mt = {}
volumegroup.__index = mt

mt.type = 'volumegroup'
mt.name = ''

function volumegroup.init()
	local volumegroup_names={}
	for i = 1, #volumegroup_names do
		local vo = {}
		vo.name = volumegroup_names[i]
		setmetatable(vo, volumegroup)
		table.insert(volumegroup, vo)
	end
end

return volumegroup