---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/06 11:47
---

local widgetevent = {}

local mt = {}
widgetevent.__index = mt

mt.type = 'widgetevent'
mt.name = ''

function widgetevent.init()
	local widgetevent_names={}
	for i = 1, #widgetevent_names do
		local wi = {}
		wi.name = widgetevent_names[i]
		setmetatable(wi, widgetevent)
		table.insert(widgetevent, wi)
	end
end

return widgetevent