---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/17 0017 9:22
---

game = game or {}
game.point = {
    release = et.point(-910, 750), -- 从监狱释放的地点

}