---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/15 9:45
---

game = game or {}
game.variable = {
    wave = 1, -- 波数
    player_count = 5, -- 游戏人数
    stop_time = 0, -- 停怪时间，以分钟为单位
}