---
--- 普通任务
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/10 15:51
---

combined_task = {
    newbee = {
        name_set = set:new { '杀野狼', '少林练功房', '拜访郭靖' },
        limit = 1,
        complete_hint = "|cFFFFCC00店小二：|r |cFF99FFCC你已经完成新手任务了",
    },
    propose = {
        name_set = set:new { '帮郭靖求婚' }
    },
    steal = {
        name_set = set:new { '偷玉箫' }
    },
    deliver = {
        name_set = set:new { '送信黄蓉', '送信郭靖', '送信达摩祖师' },
        limit = 3,
        complete_hint = "|cFFFF0000你无法再接取此任务了"
    },
    hunt = {
        name_set = set:new { '上山打猎' }
    },
    escort = {
        name_set = set:new { '押镖丘处机', '击杀豺狼', '押镖慕容复', '击杀蝎子王', '押镖达摩祖师', '押镖乔峰', '击杀进攻怪' },
        limit = 7,
        complete_hint = "|cFFFF0000你无法再接取此任务了"
    },
    bear = {
        name_set = set:new { '击杀野熊' },
        limit = 1,
        complete_hint = "|cFfff0000这个任务你已经完成过了",
    },
    collect = {
        name_set = set:new { '采集断肠草' }
    },
    protect = {
        name_set = set:new { '护送耶律楚材' },
        limit = 1,
        complete_hint = "|cFFFF0000你已经完成了这个任务了（不可重复接取）"
    },
    dumb = {
        name_set = set:new { '杀哑仆' }
    },
    maze = {
        name_set = set:new { '高昌迷宫' },
        limit = 1,
        complete_hint = "|cFfff0000这个任务你无法再接取了"
    },
    pioneer = {
        name_set = set:new { '辽国第一先锋' },
        limit = 5,
        complete_hint = "|cFfff0000任务次数达到上限，无法再次接取"
    }

}

task_map = {
    [1227895349] = 'newbee',
    [1227897172] = 'propose',
    [1227897173] = 'steal',
    [1227895898] = 'deliver',
    [1227895352] = 'hunt',
    [1227895353] = 'escort',
    [1227896132] = 'bear',
    [1227895890] = 'collect',
    [1227896387] = 'protect',
    [1227897175] = 'dumb',
    [1227896388] = 'maze',
    [1227896389] = 'pioneer',
},

--- 接取任务
--- @param u unit
--- @param it item
et.game:event '单位-捡起物品'(function(self, u, it)
    if not u:is_hero() then
        return
    end
    if task_map[it:get_id()] then
        evaluate_task(u, combined_task[task_map[it:get_id()]])
    end
end)

----------------------------------------------------------
--- 拜访类任务
----------------------------------------------------------

local visit_awards = {
    ['拜访郭靖'] = {
        show_hint = true,
        exp = 100,
        reputation = 10,
        items = { { [1227895348] = 85, [1227899720] = 15 }, }
    },
    ['送信郭靖'] = {
        show_hint = true,
        exp = 100,
        reputation = 15,
        items = { { [1227896631] = 80 }, }
    },
    ['送信黄蓉'] = {
        show_hint = true,
        exp = 100,
        reputation = 15,
        items = { { [1227896631] = 80 }, }
    },
    ['送信达摩祖师'] = {
        show_hint = true,
        exp = 100,
        reputation = 15,
        items = { { [1227896631] = 80 }, }
    },
    ['押镖丘处机'] = {
        show_hint = true,
        exp = 300,
        reputation = 25,
    },
    ['押镖慕容复'] = {
        show_hint = true,
        exp = 300,
        reputation = 25,
    },
    ['押镖达摩祖师'] = {
        show_hint = true,
        exp = 300,
        reputation = 25,
    },
    ['押镖乔峰'] = {
        show_hint = true,
        exp = 300,
        reputation = 25,
    },
}

local visit_map = {
    [GUO_JING] = { '拜访郭靖', '送信郭靖' },
    [HUANG_RONG] = { '送信黄蓉' },
    [DAMO] = { '送信达摩祖师', '押镖达摩祖师' },
    [QIU_CHUJI] = { '押镖丘处机' },
    [MURONG_FU] = { '押镖慕容复' },
    [QIAO_FENG] = { '押镖乔峰' },
}

--- 为NPC增加接近的监听器
GUO_JING:add_approach_listener()
HUANG_RONG:add_approach_listener()
DAMO:add_approach_listener()
QIU_CHUJI:add_approach_listener()
MURONG_FU:add_approach_listener()
QIAO_FENG:add_approach_listener()

--- 检查任务是否完成
--- @param name_list table<number, string>
local function check_complete_visit_task(u, name_list)
    local p = u:get_owner()
    local h = p.hero
    for _, task_name in ipairs(name_list) do
        if h.ongoing_tasks:contains(task_name) then
            PlaySoundOnUnitBJ(Hh, 100, approach.handle)
            h:add_awards(visit_awards[task_name])
            h.ongoing_tasks:remove(task_name)
            h.done_tasks:insert(task_name)
        end
    end
end

---
--- @param source unit 被接近的单位
--- @param approach unit 接近的单位
et.game:event '单位-被接近'(function(self, source, approach)
    if not approach:is_hero() then
        return
    end
    if visit_map[source] then
        check_complete_visit_task(approach, visit_map[source])
    end
end)

----------------------------------------------------------
--- 拜访类任务
----------------------------------------------------------