---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/13 9:31
---

require('test.test-main')

local trigger_util = require 'jass.util.trigger_util'


local function test_chat()

    trigger_util.trig_player_chat_event(et.player(1).handle, "+")
    trigger_util.trig_player_chat_event(et.player(1).handle, "+")

end

test_chat()