---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/29 10:23
---

require 'util.id'
local function get_center_point(tab)
    local x = (tab[1] + tab[3]) / 2
    local y = (tab[2] + tab[4]) / 2
    print(x, ',', y)
end

get_center_point { -1056.0, 5024.0, -448.0, 5600.0 }
local id_list = {
    ['1227895109'] = 0,
    ['1227895110'] = 0,
    ['1227895123'] = 0,
    ['1227895344'] = 0,
    ['1227895345'] = 0,
    ['1227895094'] = 1,
    ['1227895116'] = 1,
    ['1227895118'] = 1,
    ['1227895091'] = 2,
    ['1227895878'] = 2,
    ['1227894872'] = 3,
    ['1227897145'] = 3,
    ['1227897153'] = 3,
    ['1227894864'] = 4,
    ['1227894865'] = 4,
    ['1227894850'] = 5,
    ['1227894851'] = 5,
    ['1227894852'] = 5,
    ['1227896918'] = 5,
    ['1227897143'] = 6,
    ['1227897144'] = 6,
    ['1227897154'] = 6,
    ['1227897155'] = 6,
    ['1227897156'] = 6, }

local function id2string(...)
    for i, v in ipairs({ ... }) do
        print(base.id2string(v))
    end
end

local function test()
    id2string(1227897174, 1227896922, 1227897136)

    --for k, v in pairs(id_list) do
    --    print(base.id2string(k), v)
    --end
    print(get_center_point { -13568.0, 2272.0, -13440.0, 2400.0})
end
test()