---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/29 10:23
---

t = { a = 2 }
s = { c = 4}
mt = { __index = { b = 3} }
setmetatable(t, mt)
setmetatable(s, mt)

t.b = "c"

print(t.b)
print(getmetatable(t).__index.b)
print(s.b)



