---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/9 9:58
---

-- 请使用resources文件下的lua

local config = require 'test_frame.jass.config'
local SCRIPT_PATH = config.SCRIPT_PATH

package.path = package.path .. ';'..SCRIPT_PATH..'?.lua'
package.path = package.path .. ';'..SCRIPT_PATH..'scripts\\?.lua'
package.path = package.path .. ';'..SCRIPT_PATH..'scripts\\test_frame\\?.lua'
package.cpath = package.cpath .. ';'..SCRIPT_PATH..'scripts\\test_frame\\jass\\clib\\?.dll'

local clib = require('clib')
local o_require = require

-- 重写require函数，可以加载中文路径
function require(modname)
    flag, r = pcall(o_require, modname)
    if not flag then
        r = o_require(clib.u2g(modname))
    end
    return r
end

require('scripts.main')


