---
--- 门派
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/10/29 10:13
---

local denomination = {}
setmetatable(denomination, denomination)
et.denomination = denomination

local mt = {}
denomination.__index = mt

mt.item_id = 0
mt.id = 1
mt.name = ''
mt['悟性'] = 0
mt['根骨'] = 0
mt['医术'] = 0
mt['胆魄'] = 0
mt['福缘'] = 0
mt['经脉'] = 0
mt['自由属性'] = 0

function denomination.create()
    et.lni_loader('denomination')
    for k, v in pairs(et.lni.denomination) do
        v.name = k
    end
    local temp = {}
    for k, v in pairs(et.lni.denomination) do
        if v.item_id then
            temp[v.item_id] = v
        end
    end
    for k, v in pairs(temp) do
        et.lni.denomination[k] = temp[k]
    end
    for k, v in pairs(et.lni.denomination) do
        setmetatable(v, denomination)
    end
end

return denomination

