---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/28 0028 17:05
---

force = {}

function force.send_message(text, time)
    for i = 1, 16 do
        et.player[i]:send_message(text, time)
    end
end

function force.pingMinimap(x, y, time, red, green, blue, flag)
    for i = 1, 16 do
        et.player[i]:pingMinimap(x, y, time, red, green, blue, flag)
    end
end