---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/28 0028 16:45
---
local item = {}
setmetatable(item, item)

et.item = item

local mt = {}
item.__index = mt


-- jass的item
mt.handle = 0

-- item的id
mt.id = 0