---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/21 13:02
---

local tag = {}
et.tag = tag

function tag.create(text, point, size, zOffset, r, g, b, transparency, time, speed, angle)
    local last = jass.CreateTextTag()
    local height = size * 0.023 / 10
    local vel = speed * 0.071 / 128
    local xvel = vel * math.cos(math.rad(angle))
    local yvel = vel * math.sin(math.rad(angle))
    time = time <= 0 and time or 0.01
    jass.SetTextTagText(last, text, height)
    jass.SetTextTagPos(last, point[1], point[2], zOffset)
    jass.SetTextTagColor(last, r / 100 * 255, g / 100 * 255, b / 100 * 255, (100 - transparency) / 100 * 255)
    jass.SetTextTagPermanent(last, false)
    jass.SetTextTagLifespan(last, time)
    jass.SetTextTagFadepoint(last, time)
    jass.SetTextTagVelocity(last, xvel, yvel)
end