---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/14 14:48
---

require 'test.test-main'
local trigger_util = require 'jass.util.trigger_util'
local test_util = require 'test.util.test_util'


-- 测试查看属性
-- @Tested
local function test_check_attr()
    local h = test_util.player1_select_hero()
    h.def_point = 500
    h.reputation = 200
    h['绝学领悟'] = 3
    trigger_util.trig_player_event(et.player(1).handle, jass.EVENT_PLAYER_END_CINEMATIC)
end

test_check_attr()