---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/13 18:22
---

require 'test.test-main'
local trigger_util = require 'jass.util.trigger_util'
local item = require 'jass.type.item'
require 'util.id'

--@Tested
local function test_selectdenomination()
    trigger_util.trig_player_unit_event(et.player(1).handle, jass.EVENT_PLAYER_UNIT_SELECTED, LAN_XIN.handle)
    trigger_util.trig_player_unit_event(et.player(1).handle, jass.EVENT_PLAYER_UNIT_SELECTED, LAN_XIN.handle)
    local it = item.create(1227896664, 0, 0)
    et.player(1).hero.handle.hero=true
    trigger_util.trig_player_unit_event(et.player(1).handle, jass.EVENT_PLAYER_UNIT_PICKUP_ITEM, et.player(1).hero.handle, {manipulated_item=it})
end

test_selectdenomination()