---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/15 0015 22:43
---

require 'test.test-main'
local trigger_util = require 'jass.util.trigger_util'
local item = require 'jass.type.item'
local test_util = require 'test.util.test_util'

--- @type hero
local h
--- @type unit
local hu
--- @type player
local p
--- @type j_item
local it

local function setup()
    h = test_util.player1_select_hero()
    hu = h:get_unit()
    p = h:get_owner()
    it = item.create(1227895856, 0, 0)
    trigger_util.trig_player_unit_event(p.handle, jass.EVENT_PLAYER_UNIT_PICKUP_ITEM, h.handle, { manipulated_item = item.create(1227894833, 0, 0) })
end

local function test_pet_skill()
    print(h['伴侣'])
    -- 切换背包
    trigger_util.trig_player_unit_event(p.handle, jass.EVENT_PLAYER_UNIT_SPELL_CAST, h['伴侣'].handle, { spell_ability_id = 1093677134 })

    -- 切换物品
    trigger_util.trig_player_unit_event(p.handle, jass.EVENT_PLAYER_UNIT_SPELL_CAST, h['伴侣'].handle, { spell_ability_id = 1093677133 })

    -- 鸟的贩卖技能
    trigger_util.trig_player_unit_event(p.handle, jass.EVENT_PLAYER_UNIT_SPELL_EFFECT, h['伴侣'].handle, { spell_ability_id = 1093679433, spell_target = hu.handle.items[1] })
end

local function teardown()

end

local function test()
    setup()
    test_pet_skill()
    teardown()
end

test()