---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/19 15:30
---

require 'test.test-main'
local trigger_util = require 'jass.util.trigger_util'
local test_util = require 'test.util.test_util'

local function test_xp_rune()
    local h = test_util.player1_select_hero()
    h.handle.hero = true
    trigger_util.trig_player_unit_event(et.player(1).handle, jass.EVENT_PLAYER_UNIT_PICKUP_ITEM,
            h.handle, {manipulated_item = test_util.create_item(1952807024)})
end

test_xp_rune()