---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G.Seinfeld.
--- DateTime: 2018/11/18 0018 16:39
---

require 'test.test-main'
local trigger_util = require 'jass.util.trigger_util'
local test_util = require 'test.util.test_util'

local function test_pawn_attack_creep()
    local h = test_util.player1_select_hero()
    test_util.update_timer(nil, 41)
    test_util.update_timer(nil, 120)
    test_util.update_timer(nil, 80)
    test_util.update_timer(nil, 95)
    test_util.update_timer(nil, 30)
    --test_util.update_timer(nil, 130)
end

test_pawn_attack_creep()