---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/17 0017 12:08
---

require 'test.test-main'
local trigger_util = require 'jass.util.trigger_util'
local test_util = require 'test.util.test_util'

local function test_partner_system()
    local h = test_util.player1_select_hero()
    local it = test_util.create_item(1227899447)
end
test_partner_system()