---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:30
---

--反两仪刀法
function yG()
    return GetSpellAbilityId() == 1093678920 and IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) ~= nil -- INLINED!!
end
function zG()
    local id = GetHandleId(GetTriggeringTrigger())
    local cx = LoadInteger(YDHT, id, -807506826)
    cx = cx + 3
    SaveInteger(YDHT, id, -807506826, cx)
    SaveInteger(YDHT, id, -320330265, cx)
    SaveUnitHandle(YDHT, id * cx, 1505665227, GetTriggerUnit())
    SaveLocationHandle(YDHT, id * cx, 1585647951, GetUnitLoc(LoadUnitHandle(YDHT, id * cx, 1505665227)))
    SaveInteger(YDHT, id * cx, -708948899, 1093678920)
    CreateNUnitsAtLoc(1, 1697656880, GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)), LoadLocationHandle(YDHT, id * cx, 1585647951), bj_UNIT_FACING)
    UnitAddAbility(bj_lastCreatedUnit, 1093681495)
    IssueTargetOrderById(bj_lastCreatedUnit, 852066, LoadUnitHandle(YDHT, id * cx, 1505665227))
    UnitApplyTimedLife(bj_lastCreatedUnit, 1112045413, 2.0)
    ShowUnitHide(bj_lastCreatedUnit)
    RemoveLocation(LoadLocationHandle(YDHT, id * cx, 1585647951))
    WuGongShengChong(GetTriggerUnit(), 1093678920, 90.0)
    YDWELocalVariableEnd()
    FlushChildHashtable(YDHT, id * cx)
end
function aG()
    return GetEventDamage() == 4.13
end
function BG()
    local i = 1 + GetPlayerId(GetOwningPlayer(GetEventDamageSource()))
    local u = udg_hero[i]
    local uc = GetTriggerUnit()
    local shxishu = jueXueXiShu(i)
    local shanghai = 0.0
    shanghai = ShangHaiGongShi(u, uc, 50.0, 50.0, shxishu, 1093678920)
    WuGongShangHai(u, uc, shanghai)
    u = nil
    uc = nil
end

t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_SPELL_EFFECT)
TriggerAddCondition(t, Condition(yG))
TriggerAddAction(t, zG)
t = CreateTrigger()
YDWESyStemAnyUnitDamagedRegistTrigger(t)
TriggerAddCondition(t, Condition(aG))
TriggerAddAction(t, BG)