---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:35
---

--打狗棒法
function O6()
    return GetSpellAbilityId() == 1093678924
end
function P6()
    return IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(C9)) and IsUnitAliveBJ(GetFilterUnit())
end
function Q6()
    local u = C9
    local uc = GetEnumUnit()
    local i = 1 + GetPlayerId(GetOwningPlayer(u))
    local shxishu = jueXueXiShu(i)
    local shanghai = 0.0
    if UnitHaveItem(u, 1227897143) then
        shxishu = shxishu * 8
    end
    shanghai = ShangHaiGongShi(u, uc, 35.0, 35.0, shxishu, 1093678924)
    WuGongShangHai(u, uc, shanghai)
    u = nil
    uc = nil
end
function R6()
    local id = GetHandleId(GetTriggeringTrigger())
    local cx = LoadInteger(YDHT, id, -807506826)
    cx = cx + 3
    SaveInteger(YDHT, id, -807506826, cx)
    SaveInteger(YDHT, id, -320330265, cx)
    DisableTrigger(GetTriggeringTrigger())
    C9 = GetTriggerUnit()
    c9 = GetUnitLoc(GetTriggerUnit())
    SaveUnitHandle(YDHT, id * cx, 1505665227, GetTriggerUnit())
    SaveInteger(YDHT, id * cx, -708948899, 1093678924)
    SaveReal(YDHT, id * cx, -753873030, 1.8 + I2R(juexuelingwu[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))]) + I2R(GetUnitAbilityLevel(LoadUnitHandle(YDHT, id * cx, 1505665227), LoadInteger(YDHT, id * cx, -708948899))) / 2.0 + I2R(gengu[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))]) * 0.06)
    SaveReal(YDHT, id * cx, 426308609, 9.0 + udg_shanghaijiacheng[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))])
    SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * LoadReal(YDHT, id * cx, 426308609))
    SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * 1.5)
    if GetUnitAbilityLevel(LoadUnitHandle(YDHT, id * cx, 1505665227), LoadInteger(YDHT, id * cx, -708948899)) == 9 then
        SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * 10.0)
    end
    WuGongShengChong(GetTriggerUnit(), 1093678924, 70.0)
    TriggerSleepAction(0.2)
    SaveInteger(YDHT, id, -320330265, cx)
    PauseUnit(C9, true)
    CreateNUnitsAtLoc(1, 1747988532, GetOwningPlayer(C9), c9, bj_UNIT_FACING)
    D9 = bj_lastCreatedUnit
    SetUnitPositionLocFacingLocBJ(C9, pu(c9, 800.0, 135.0), c9)
    SetUnitAnimation(C9, "ATTACK")
    SetUnitPositionLocFacingLocBJ(D9, GetUnitLoc(C9), GetUnitLoc(C9))
    TriggerSleepAction(0.15)
    SaveInteger(YDHT, id, -320330265, cx)
    SetUnitPositionLocFacingLocBJ(C9, pu(c9, 800.0, 45.0), c9)
    SetUnitAnimation(C9, "ATTACK")
    SetUnitPositionLocFacingLocBJ(D9, GetUnitLoc(C9), GetUnitLoc(C9))
    TriggerSleepAction(0.15)
    SaveInteger(YDHT, id, -320330265, cx)
    SetUnitPositionLocFacingLocBJ(C9, pu(c9, 600.0, 225.0), c9)
    SetUnitAnimation(C9, "ATTACK")
    SetUnitPositionLocFacingLocBJ(D9, GetUnitLoc(C9), GetUnitLoc(C9))
    TriggerSleepAction(0.15)
    SaveInteger(YDHT, id, -320330265, cx)
    SetUnitPositionLocFacingLocBJ(C9, pu(c9, 900.0, 90.0), c9)
    SetUnitAnimation(C9, "ATTACK")
    SetUnitPositionLocFacingLocBJ(D9, GetUnitLoc(C9), GetUnitLoc(C9))
    TriggerSleepAction(0.15)
    SaveInteger(YDHT, id, -320330265, cx)
    SetUnitPositionLocFacingLocBJ(C9, pu(c9, 600.0, 315.0), c9)
    SetUnitAnimation(C9, "ATTACK")
    SetUnitPositionLocFacingLocBJ(D9, GetUnitLoc(C9), GetUnitLoc(C9))
    TriggerSleepAction(0.15)
    SaveInteger(YDHT, id, -320330265, cx)
    SetUnitPositionLocFacingLocBJ(GetTriggerUnit(), pu(c9, 800.0, 135.0), c9)
    SetUnitAnimation(C9, "ATTACK")
    SetUnitPositionLocFacingLocBJ(D9, GetUnitLoc(C9), GetUnitLoc(C9))
    TriggerSleepAction(0.15)
    SaveInteger(YDHT, id, -320330265, cx)
    AddLightningLoc("FORK", pu(c9, 800.0, 135.0), pu(c9, 800.0, 45.0))
    E9[1] = bj_lastCreatedLightning
    AddLightningLoc("FORK", pu(c9, 800.0, 45.0), pu(c9, 600.0, 225.0))
    E9[2] = bj_lastCreatedLightning
    AddLightningLoc("FORK", pu(c9, 600.0, 225.0), pu(c9, 900.0, 90.0))
    E9[3] = bj_lastCreatedLightning
    AddLightningLoc("FORK", pu(c9, 900.0, 90.0), pu(c9, 600.0, 315.0))
    E9[4] = bj_lastCreatedLightning
    AddLightningLoc("FORK", pu(c9, 600.0, 315.0), pu(c9, 800.0, 135.0))
    E9[5] = bj_lastCreatedLightning
    SetUnitPositionLocFacingLocBJ(C9, c9, c9)
    RemoveUnit(D9)
    F9 = 1
    for _ in _loop_() do
        if F9 > 12 then break end
        AddSpecialEffectLocBJ(pu(c9, 100.0, 30.0 * I2R(F9)), "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl")
        DestroyEffect(bj_lastCreatedEffect)
        AddSpecialEffectLocBJ(pu(c9, 300.0, 30.0 * I2R(F9)), "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl")
        DestroyEffect(bj_lastCreatedEffect)
        AddSpecialEffectLocBJ(pu(c9, 500.0, 30.0 * I2R(F9)), "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl")
        DestroyEffect(bj_lastCreatedEffect)
        F9 = F9 + 1
    end
    ForGroupBJ(YDWEGetUnitsInRangeOfLocMatchingNull(600.0, c9, Condition(P6)), Q6)
    TriggerSleepAction(1.0)
    SaveInteger(YDHT, id, -320330265, cx)
    DestroyLightning(E9[1])
    DestroyLightning(E9[2])
    DestroyLightning(E9[3])
    DestroyLightning(E9[4])
    DestroyLightning(E9[5])
    PauseUnit(C9, false)
    ResetUnitAnimation(C9)
    EnableTrigger(jn)
    TriggerSleepAction(6.0)
    SaveInteger(YDHT, id, -320330265, cx)
    DisableTrigger(jn)
    RemoveLocation(c9)
    EnableTrigger(in_)
    FlushChildHashtable(YDHT, id * cx)
end
function T6()
    return IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(C9)) and IsUnitAliveBJ(GetFilterUnit())
end
function U6()
    local u = C9
    local uc = GetEnumUnit()
    local i = 1 + GetPlayerId(GetOwningPlayer(u))
    local shxishu = jueXueXiShu(i)
    local shanghai = 0.0
    shanghai = ShangHaiGongShi(u, uc, 18.0, 18.0, shxishu, 1093678924)
    WuGongShangHai(u, uc, shanghai)
    u = nil
    uc = nil
end
function V6()
    local id = GetHandleId(GetTriggeringTrigger())
    local cx = LoadInteger(YDHT, id, -807506826)
    cx = cx + 3
    SaveInteger(YDHT, id, -807506826, cx)
    SaveInteger(YDHT, id, -320330265, cx)
    SaveUnitHandle(YDHT, id * cx, 1505665227, C9)
    SaveInteger(YDHT, id * cx, -708948899, 1093678924)
    SaveLocationHandle(YDHT, id * cx, 1585647951, pu(GetUnitLoc(LoadUnitHandle(YDHT, id * cx, 1505665227)), GetRandomReal(100.0, 350.0), GetRandomReal(0, 360.0)))
    CreateNUnitsAtLoc(1, 1697656905, GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)), LoadLocationHandle(YDHT, id * cx, 1585647951), bj_UNIT_FACING)
    Gw(2.0, bj_lastCreatedUnit)
    SaveReal(YDHT, id * cx, -753873030, 1.8 + I2R(juexuelingwu[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))]) + I2R(GetUnitAbilityLevel(LoadUnitHandle(YDHT, id * cx, 1505665227), LoadInteger(YDHT, id * cx, -708948899))) / 2.0 + I2R(gengu[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))]) * 0.06)
    SaveReal(YDHT, id * cx, 426308609, 9.0 * udg_shanghaijiacheng[1 + GetPlayerId(GetOwningPlayer(LoadUnitHandle(YDHT, id * cx, 1505665227)))])
    SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * LoadReal(YDHT, id * cx, 426308609))
    SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * 1.5)
    if GetUnitAbilityLevel(LoadUnitHandle(YDHT, id * cx, 1505665227), LoadInteger(YDHT, id * cx, -708948899)) == 9 then
        SaveReal(YDHT, id * cx, -753873030, LoadReal(YDHT, id * cx, -753873030) * 10.0)
    end
    ForGroupBJ(YDWEGetUnitsInRangeOfLocMatchingNull(400.0, LoadLocationHandle(YDHT, id * cx, 1585647951), Condition(T6)), U6)
    FlushChildHashtable(YDHT, id * cx)
end

in_ = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(in_, EVENT_PLAYER_UNIT_SPELL_EFFECT)
TriggerAddCondition(in_, Condition(O6))
TriggerAddAction(in_, R6)
jn = CreateTrigger()
DisableTrigger(jn)
TriggerRegisterTimerEventPeriodic(jn, 0.3)
TriggerAddAction(jn, V6)