---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:33
---

--- 胡家刀法
--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target unit|point|nil 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093679158 and u:is_hero() then
        for i = 1, 18 do
            dummy_issue_order {
                target = u:get_point() - { 20 * i, 256 },
                player = u:get_owner(),
                unit_id = 1697656880,
                ability_id = 1093679159,
                order_id = 852218,
                lifetime = 2,
            }
        end
        local h = u:get_owner().hero
        et.timer(300, 50, function()
            local last = u:get_owner():create_unit(1697656908, u:get_point() - { commonutil.random(0, 360), commonutil.random(100, 350) })
            last:set_lifetime(2)
            local group = et.selector():in_range(last:get_point(), 350):is_enemy(u):get()
            for _, v in pairs(group) do
                local ability_damage, critical = damage_formula {
                    source = u,
                    target = v,
                    magic_coeff = 1,
                    physic_coeff = 1,
                    ability_coeff = 20 * outstanding_kungfu_coeff(h),
                    level = u:get_ability_level(1093679158)
                }
                apply_damage(u, v, ability_damage, critical)
            end
        end)
    end
end)
