---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:33
---

--- 西毒杖法
--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target unit|point|nil 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093679161 and u:is_hero() then
        dummy_issue_order {
            player = u:get_owner(),
            unit_id = 1697656909,
            ability_id = 1093679160,
            order_id = 852183,
            lifetime = 31,
            shown = true
        }
    end
end)

--- 西毒杖法伤害
--- @param source unit 伤害来源
--- @param target unit 受伤害的单位
--- @param damage number 伤害的数值
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if damage == 4.35 then
        local h = source:get_owner().hero
        local coeff = outstanding_kungfu_coeff(h)
        if source:has_item(1227897154) then
            coeff = coeff * 3
        end
        local ability_damage, critical = damage_formula {
            source = source,
            target = target,
            magic_coeff = 1,
            physic_coeff = 1,
            ability_coeff = 45 * coeff,
            level = source:get_ability_level(1093679161)
        }
        apply_damage(source, target, ability_damage, critical)
    end
end)
