---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:33
---

--西毒杖法
function e6()
    return GetSpellAbilityId() == 1093679161 and IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) ~= nil -- INLINED!!
end
function f6()
    local u = GetTriggerUnit()
    local loc = GetUnitLoc(u)
    CreateNUnitsAtLoc(1, 1697656909, GetOwningPlayer(u), loc, bj_UNIT_FACING)
    UnitAddAbility(bj_lastCreatedUnit, 1093679160)
    IssueImmediateOrderById(bj_lastCreatedUnit, 852183)
    UnitApplyTimedLife(bj_lastCreatedUnit, 1112045413, 31.0)
    RemoveLocation(loc)
    WuGongShengChong(GetTriggerUnit(), 1093679161, 100.0)
    u = nil
    loc = nil
end
function h6()
    return GetEventDamage() == 4.35
end
function i6()
    local i = 1 + GetPlayerId(GetOwningPlayer(GetEventDamageSource()))
    local u = udg_hero[i]
    local uc = GetTriggerUnit()
    local shxishu = jueXueXiShu(i)
    local shanghai = 0.0
    if UnitHaveItem(u, 1227897154) then
        shxishu = shxishu * 8
    end
    shanghai = ShangHaiGongShi(u, uc, 45.0, 45.0, shxishu, 1093679161)
    WuGongShangHai(u, uc, shanghai)
    u = nil
    uc = nil
end

t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_SPELL_EFFECT)
TriggerAddCondition(t, Condition(e6))
TriggerAddAction(t, f6)
t = CreateTrigger()
YDWESyStemAnyUnitDamagedRegistTrigger(t)
TriggerAddCondition(t, Condition(h6))
TriggerAddAction(t, i6)