---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:31
---

local set = require('util.collection.set')

local ye_qiu_set = set:new()

--- 野球拳
--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target unit|point|nil 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093678921 and u:is_hero() then
        local function dummy_turn_around(angle)
            local last = u:get_owner():create_unit(1697656904, u:get_point() - { angle, 325 })
            last:set_lifetime(20)
            turn_around(last, u, 6, 0, 0, 20, 0.03)
        end
        dummy_turn_around(0)
        dummy_turn_around(120)
        dummy_turn_around(240)
        ye_qiu_set:insert(u)
        et.wait(2000, function()
            ye_qiu_set:remove(u)
        end)
    end
end)

--- 野球拳伤害
et.loop(300, function()
    if ye_qiu_set:is_empty() then
        return
    end
    for u, _ in pairs(ye_qiu_set) do
        local group = et.selector():in_range(u:get_point(), 650):is_enemy(u):get()
        local h = u:get_owner().hero
        for _, v in pairs(group) do
            et.effect.add_to_point("war3mapImported\\CrimsonWake.mdx", v:get_point()):destroy()
            local ability_damage, critical = damage_formula {
                source = u,
                target = v,
                magic_coeff = 1,
                physic_coeff = 1,
                ability_coeff = 30 * outstanding_kungfu_coeff(h),
                level = u:get_ability_level(1093678921)
            }
            apply_damage(u, v, ability_damage, critical)
        end
    end
end)

