---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:16
---

--- 降龙十八掌
--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target unit|point|nil 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093678917 and u:is_hero() then
        et.timer(1000, 30, function(t)
            local group = et.selector():in_range(u:get_point(), 700):is_enemy(u):get()
            local h = u:get_owner().hero
            for _, v in pairs(group) do
                et.effect.add_to_point("Abilities\\Spells\\Human\\MarkOfChaos\\MarkOfChaosTarget.mdl", v:get_point())
                local coeff = outstanding_kungfu_coeff(h)
                local ability_damage, critical = damage_formula {
                    source = u,
                    target = v,
                    magic_coeff = 1,
                    physic_coeff = 1,
                    ability_coeff = 60 * coeff,
                    level = u:get_ability_level()
                }
                apply_damage(u, v, ability_damage, critical)
            end
        end)
    end
end)
