---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:29
---

--黯然销魂掌
function sG()
    return GetSpellAbilityId() == 1093678919 and IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) ~= nil -- INLINED!!
end
function tG()
    local id = GetHandleId(GetTriggeringTrigger())
    local cx = LoadInteger(YDHT, id, -807506826)
    cx = cx + 3
    SaveInteger(YDHT, id, -807506826, cx)
    SaveInteger(YDHT, id, -320330265, cx)
    SaveUnitHandle(YDHT, id * cx, 1505665227, GetTriggerUnit())
    SaveInteger(YDHT, id * cx, -708948899, 1093678919)
    WuGongShengChong(GetTriggerUnit(), 1093678919, 90.0)
    YDWELocalVariableEnd()
    FlushChildHashtable(YDHT, id * cx)
end
function vG()
    return GetEventDamage() == 4.21
end
function wG()
    local i = 1 + GetPlayerId(GetOwningPlayer(GetEventDamageSource()))
    local u = udg_hero[i]
    local uc = GetTriggerUnit()
    local shxishu = jueXueXiShu(i)
    local shanghai = 0.0
    local loc = GetUnitLoc(uc)
    shanghai = ShangHaiGongShi(u, uc, 33.0, 33.0, shxishu, 1093678919)
    WuGongShangHai(u, uc, shanghai)
    if GetRandomInt(1, 50) >= 20 and UnitHasBuffBJ(uc, 1110454328) == false then
        general_buff(u, uc, 11)
    end
    RemoveLocation(loc)
    u = nil
    uc = nil
    loc = nil
end

t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_SPELL_EFFECT)
TriggerAddCondition(t, Condition(sG))
TriggerAddAction(t, tG)
t = CreateTrigger()
YDWESyStemAnyUnitDamagedRegistTrigger(t)
TriggerAddCondition(t, Condition(vG))
TriggerAddAction(t, wG)