---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/23 0023 21:29
---

--- @param u unit 施法单位
--- @param id number 技能ID
--- @param target unit|point|nil 技能目标
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093678919 and u:is_hero() then

    end
end)

--- 黯然销魂掌伤害
--- @param source unit 伤害来源
--- @param target unit 受伤害的单位
--- @param damage number 伤害的数值
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if damage == 4.21 then
        local coeff = outstanding_kungfu_coeff(h)
        local ability_damage, critical = damage_formula {
            source = source,
            target = target,
            magic_coeff = 1,
            physic_coeff = 1,
            ability_coeff = 33 * coeff,
            level = source:get_ability_level(1093678919)
        }
        apply_damage(source, target, ability_damage, critical)
        if commonutil.random(0, 50) >= 20 and not target:has_buff(1110454328) then
            source:apply_buff(target, "封穴")
        end
    end
end)

