---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/9 10:53
---

local console = {}

function console.write(...)
    print(...)
end

return console