---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/9 15:53
---


local config = require 'jass.config'
local SCRIPT_PATH = config.SCRIPT_PATH
local base = require 'jass.util.id'

local slk = {}
local lni = require 'jass.util.lni-loader'
local storm = require 'jass.storm'

local function lni_loader(name)
    slk[name] = lni:packager(name, storm.load)
    print('读取lni文件' .. name)
    for k, v in pairs(slk[name]) do
        if v._parent ~= k then
            if (slk[name][v._parent]) then
                for k1, v1 in pairs(slk[name][v._parent]) do
                    if not v[k1] then
                        slk[name][k][k1] = v1
                    end
                end
            end
        end
    end
end

local function init()
    lni:set_marco('TableSearcher', '$MapPath$table\\')
    lni:set_marco('MapPath', SCRIPT_PATH)
    lni_loader('ability')
    lni_loader('buff')
    lni_loader('destructable')
    lni_loader('doodad')
    lni_loader('imp')
    lni_loader('item')
    lni_loader('misc')
    lni_loader('unit')

    local item_ids = {
        'I03J',
        'I03H',
        'I02V',
        'I02U',
        'I03G',
        'I02Z',
        'I02X',
        'I03I',
        'I02Y',
        'I03K',
        'I03D',
        'I03L',
        'I030',
        'I031',
        'I03E',
        'I033',
        'I02W',
        'I03F',
        'I039',
        'I034',
        'I038',
        'I037',
        'I03B',
        'I032',
        'I035',
        'I036',
        'I03C',
        'I03A',
        'I03S',
        'I03O',
        'I03T',
        'I03Q',
        'I03M',
        'I03P',
        'I03U',
        'I03R',
        'I09G',
        'I09H',
        'I09I',
        'I09J',
        'I09K',
        'I0C2',
        'I0C3',
        'I0C4',
        'I0C5',
        'I0C6',
        'I0C8',
        'I0C9',
        'I0CA',
        'I0CB',
        'I0CC',
        'I0CD',
        'I0CJ',
        'I0CT',
        'I0CU',
        'I0CV',
    }


    local dest = io.open('dest.ini', 'w+')
    for _, v in ipairs(item_ids) do
        print(slk.item[v].Name)
    end

end
init()

return slk