---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/11/9 15:53
---

local storm = {}

function storm.load(filename)
    file = io.open(filename)
    if file then
        return file:read('*a')
    end
    return nil
end
return storm