---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/17 14:05
---

--- 金钟罩
--- @param u unit
--- @param id number
--- @param target nil
et.game:event '单位-技能生效'(function(self, u, id, target)
    if id == 1093678415 and u:is_hero() then
        local p = u:get_owner()
        local h = p.hero
        h.effects['金钟罩']:destroy()
        u:remove_ability(1110454320)
        h.jin_zhong_value = 5000 * h['医术'] * u:get_ability_level(1093678415)
        h.jin_zhong_award = 70 * u:get_ability_level(1093678415)
        u:add_bonus('armor', h.jin_zhong_award)
        if h['根骨'] >= 20 then
            h.jin_zhong_value = h.jin_zhong_value * 2
        end
        h.effects['金钟罩'] = et.effect.add_to_unit("chest", u, "war3mapImported\\DefensiveBarrierBig.mdx")
        p:send_message("|cff00ccff金钟罩效果总值：" .. h.jin_zhong_value)
    end
end)

--- @param source unit
--- @param target unit
--- @param damage number
et.game:event '单位-受到伤害'(function(self, source, target, damage)
    if target:has_buff(1110454320) then
        local p = target:get_owner()
        local h = p.hero
        local coeff = u:has_item(1227899212) and 3 or 1
        if damage < h.jin_zhong_value then
            target:set_life(target:get_life() + damage)
            h.jin_zhong_value = h.jin_zhong_value - damage
            if target:has_ability(1093678928) then
                et.effect.add_to_point("Abilities\\Spells\\Demon\\DarkPortal\\DarkPortalTarget.mdl", source:get_point()):destroy()
                local ability_damage, critical = damage_formula {
                    source = target,
                    target = source,
                    magic_coeff = 1,
                    physic_coeff = 1,
                    ability_coeff = 20 * coeff,
                    level = target:get_ability_level(1093678415)
                }
                apply_damage(target, source, ability_damage, critical)
            end
        else
            h.effects['金钟罩']:destroy()
            target:add_bonus('armor', -h.jin_zhong_award)
            --+易筋经
            if target:has_ability(1093679428) then
                local group = et.selector():in_range(target:get_point(), 600):is_enemy(target):get()
                for _, v in pairs(group) do
                    et.effect.add_to_point("Abilities\\Spells\\Undead\\DarkRitual\\DarkRitualTarget.mdl", target:get_point()):destroy()
                    local ability_damage, critical = damage_formula {
                        source = target,
                        target = v,
                        magic_coeff = 1,
                        physic_coeff = 1,
                        ability_coeff = 400 * coeff,
                        level = target:get_ability_level(1093678415)
                    }
                    apply_damage(target, v, ability_damage, critical)
                end
            end
            --+小无相
            if target:has_ability(1093679155) and commonutil.random(0, 100) >= 70 then
                h.jin_zhong_value = 2500 * h['医术'] * target:get_ability_level(1093678415)
                h.jin_zhong_award = 70 * u:get_ability_level(1093678415)
                target:add_bonus('armor', h.jin_zhong_award)
                if h['根骨'] >= 20 then
                    h.jin_zhong_value = h.jin_zhong_value * 2
                end
                h.effects['金钟罩'] = et.effect.add_to_unit("chest", u, "war3mapImported\\DefensiveBarrierBig.mdx")
                p:send_message("|cff00ccff金钟罩效果总值：" .. h.jin_zhong_value)
            else
                u:remove_ability(1110454320)
            end
        end
    end
end)

