---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2018/12/17 14:07
---

--降魔功
function lc()
    return GetUnitAbilityLevel(GetKillingUnit(), 1395666992) ~= 0
end
function Jc()
    local i = 1 + GetPlayerId(GetOwningPlayer(GetKillingUnit()))
    if jingmai[i] >= 25 then
        F7[i] = F7[i] + 1
        if F7[i] >= 10 then
            F7[i] = F7[i] - 10
            ModifyHeroStat(1, GetKillingUnit(), 0, 1)
        end
    end
end
function Lc()
    return GetUnitAbilityLevel(GetTriggerUnit(), 1395666992) ~= 0
end
function Mc()
    local u = GetTriggerUnit()
    local p = GetOwningPlayer(u)
    local i = 1 + GetPlayerId(p)
    local loc = GetUnitLoc(u)
    if GetUnitAbilityLevel(GetTriggerUnit(), 1093678936) ~= 0 then
        G7[i] = G7[i] + 1
        if G7[i] >= 10 then
            G7[i] = G7[i] - 10
            H7 = 1
            for _ in _loop_() do
                if H7 > 18 then break end
                CreateNUnitsAtLoc(1, 1697656880, GetOwningPlayer(GetTriggerUnit()), loc, bj_UNIT_FACING)
                UnitAddAbility(bj_lastCreatedUnit, 1093678416)
                IssuePointOrderByIdLoc(bj_lastCreatedUnit, 852218, pu(loc, 256, 20.0 * I2R(H7)))
                ShowUnitHide(bj_lastCreatedUnit)
                UnitApplyTimedLife(bj_lastCreatedUnit, 1112045413, 2.0)
                RemoveLocation(pu(loc, 256, 20.0 * I2R(H7)))
                H7 = H7 + 1
            end
            RemoveLocation(loc)
        end
    end
    if GetRandomReal(1, 100) <= 15 + fuyuan[i] // 5 then
        WuGongShengChong(GetTriggerUnit(), 1395666992, 6000.0)
    end
    u = nil
    p = nil
    loc = nil
end
function Oc()
    return GetUnitAbilityLevel(GetAttacker(), 1395666992) ~= 0
end
function Pc()
    local u = GetAttacker()
    local l__ut = GetTriggerUnit()
    local loc = nil
    if GetRandomInt(1, 100) <= 2 and GetUnitAbilityLevel(u, 1093678931) ~= 0 and GetUnitAbilityLevel(u, 1093682254) ~= 0 then
        loc = GetUnitLoc(l__ut)
        CreateNUnitsAtLoc(1, 1852862002, GetOwningPlayer(u), loc, bj_UNIT_FACING)
        UnitApplyTimedLife(bj_lastCreatedUnit, 1112045413, 180.0)
        RemoveLocation(loc)
    end
    if GetUnitAbilityLevel(u, 1395666994) ~= 0 then
        if GetUnitState(l__ut, UNIT_STATE_LIFE) <= 0.01 * GetUnitState(l__ut, UNIT_STATE_MAX_LIFE) then
            SetWidgetLife(l__ut, 1.0)
        else
            SetWidgetLife(l__ut, GetUnitState(l__ut, UNIT_STATE_LIFE) - 0.01 * GetUnitState(l__ut, UNIT_STATE_MAX_LIFE))
        end
    end
    u = nil
    l__ut = nil
    loc = nil
end
function Rc()
    return GetEventDamage() == 0.18
end
function Sc()
    local u = udg_hero[1 + GetPlayerId(GetOwningPlayer(GetEventDamageSource()))]
    local uc = GetTriggerUnit()
    local shxishu = 1.0
    local shanghai = 0.0
    if UnitHaveItem(u, 1227899212) then
        shxishu = shxishu * 8
    end
    shanghai = ShangHaiGongShi(u, uc, 50, 50, shxishu, 1395666992)
    WuGongShangHai(u, uc, shanghai)
    u = nil
    uc = nil
end


t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_DEATH)
TriggerAddCondition(t, Condition(lc))
TriggerAddAction(t, Jc)

t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_ATTACKED)
TriggerAddCondition(t, Condition(Lc))
TriggerAddAction(t, Mc)

t = CreateTrigger()
TriggerRegisterAnyUnitEventBJ(t, EVENT_PLAYER_UNIT_ATTACKED)
TriggerAddCondition(t, Condition(Oc))
TriggerAddAction(t, Pc)

--t = CreateTrigger()
--YDWESyStemAnyUnitDamagedRegistTrigger(t)
--TriggerAddCondition(t, Condition(Rc))
--TriggerAddAction(t, Sc)